let bannedList = ["Mbaby_baosanniang", "Mbaby_beimihu", "Mbaby_bianfuren", "Mbaby_bianyue", "Mbaby_bulianshi", "Mbaby_buzhi", "Mbaby_caifuren", "Mbaby_caiwenji", "Mbaby_caiyong", "Mbaby_caoang", "Mbaby_caoanmin", "Mbaby_caocao", "Mbaby_caohong", "Mbaby_caojie", "Mbaby_caopi", "Mbaby_caoren", "Mbaby_caorui", "Mbaby_caoxing", "Mbaby_caoxiu", "Mbaby_caoying", "Mbaby_caozhang", "Mbaby_caozhen", "Mbaby_caozhi", "Mbaby_change", "Mbaby_chendao", "Mbaby_chendeng", "Mbaby_chendong", "Mbaby_chengong", "Mbaby_chengpu", "Mbaby_chengyu", "Mbaby_chenlin", "Mbaby_chenqun", "Mbaby_chentai", "Mbaby_chunyuqiong", "Mbaby_dalanmao", "Mbaby_daqiao", "Mbaby_dc_huangchengyan", "Mbaby_dc_huangzu", "Mbaby_dc_sunru", "Mbaby_dc_yanghu", "Mbaby_dengai", "Mbaby_dengzhi", "Mbaby_dianwei", "Mbaby_diaochan", "Mbaby_dingfeng", "Mbaby_dongbai", "Mbaby_dongxie", "Mbaby_dongyun", "Mbaby_dongzhuo", "Mbaby_duanwei", "Mbaby_dufuren", "Mbaby_fanchou", "Mbaby_fazheng", "Mbaby_fuhuanghou", "Mbaby_fuwan", "Mbaby_ganfurenmifuren", "Mbaby_ganning", "Mbaby_gaolan", "Mbaby_gaoshun", "Mbaby_gexuan", "Mbaby_gongsunyuan", "Mbaby_gongsunzan", "Mbaby_guanlu", "Mbaby_guanning", "Mbaby_guanping", "Mbaby_guanqiujian", "Mbaby_guansuo", "Mbaby_guanyinping", "Mbaby_guanzhang", "Mbaby_guohuai", "Mbaby_guohuanghou", "Mbaby_guojia", "Mbaby_guosi", "Mbaby_guotufengji", "Mbaby_hanhaoshihuan", "Mbaby_heqi", "Mbaby_hetaihou", "Mbaby_huaman", "Mbaby_huangfusong", "Mbaby_huanggai", "Mbaby_huanghao", "Mbaby_huangyueying", "Mbaby_huangzhong", "Mbaby_huatuo", "Mbaby_huaxiong", "Mbaby_hujinding", "Mbaby_jiangfei", "Mbaby_jianggan", "Mbaby_jiangqing", "Mbaby_jiangwei", "Mbaby_jianyong", "Mbaby_jiaxu", "Mbaby_jingwei", "Mbaby_jsp_guanyu", "Mbaby_jsp_huangyueying", "Mbaby_jushou", "Mbaby_kanze", "Mbaby_kuailiangkuaiyue", "Mbaby_laiyinger", "Mbaby_leitong", "Mbaby_liangxing", "Mbaby_liaohua", "Mbaby_libai", "Mbaby_licaiwei", "Mbaby_lidian", "Mbaby_lijue", "Mbaby_liru", "Mbaby_liubei", "Mbaby_liubian", "Mbaby_liubiao", "Mbaby_liuchen", "Mbaby_liufeng", "Mbaby_liushan", "Mbaby_liuxie", "Mbaby_liuye", "Mbaby_liuyong", "Mbaby_liuzhang", "Mbaby_liyan", "Mbaby_luji", "Mbaby_lukang", "Mbaby_lusu", "Mbaby_luxun", "Mbaby_luyusheng", "Mbaby_lvbu", "Mbaby_lvdai", "Mbaby_lvfan", "Mbaby_lvkai", "Mbaby_lvmeng", "Mbaby_machao", "Mbaby_madai", "Mbaby_masu", "Mbaby_mayunlu", "Mbaby_mazhong", "Mbaby_menghuo", "Mbaby_mengjie", "Mbaby_mifuren", "Mbaby_mizhu", "Mbaby_nvwa", "Mbaby_ol_dingyuan", "Mbaby_ol_sb_guanyu", "Mbaby_ol_sb_jiangwei", "Mbaby_ol_sunjian", "Mbaby_panfeng", "Mbaby_pangde", "Mbaby_pangtong", "Mbaby_panjun", "Mbaby_panzhangmazhong", "Mbaby_qinmi", "Mbaby_quancong", "Mbaby_quanhuijie", "Mbaby_quyi", "Mbaby_re_guyong", "Mbaby_re_hansui", "Mbaby_re_jsp_pangtong", "Mbaby_re_nanhualaoxian", "Mbaby_re_pangdegong", "Mbaby_re_sunyi", "Mbaby_ruanyu", "Mbaby_sb_caocao", "Mbaby_sb_ganning", "Mbaby_sb_guojia", "Mbaby_sb_huanggai", "Mbaby_sb_huangyueying", "Mbaby_sb_huangzhong", "Mbaby_sb_huaxiong", "Mbaby_sb_liubei", "Mbaby_sb_lvmeng", "Mbaby_sb_machao", "Mbaby_sb_sunquan", "Mbaby_sb_sunshangxiang", "Mbaby_sb_xuhuang", "Mbaby_sb_yuanshao", "Mbaby_sb_yujin", "Mbaby_sb_zhaoyun", "Mbaby_shamoke", "Mbaby_shen_caocao", "Mbaby_shen_daxiaoqiao", "Mbaby_shen_dengai", "Mbaby_shen_dianwei", "Mbaby_shen_diaochan", "Mbaby_shen_ganning", "Mbaby_shen_guanyu", "Mbaby_shen_guojia", "Mbaby_shen_liubei", "Mbaby_shen_lusu", "Mbaby_shen_luxun", "Mbaby_shen_lvbu", "Mbaby_shen_lvmeng", "Mbaby_shen_pangtong", "Mbaby_shen_simayi", "Mbaby_shen_sunquan", "Mbaby_shen_taishici", "Mbaby_shen_zhangliao", "Mbaby_shen_zhaoyun", "Mbaby_shen_zhenji", "Mbaby_shen_zhouyu", "Mbaby_shen_zhugeliang", "Mbaby_simahui", "Mbaby_simalang", "Mbaby_simayi", "Mbaby_sp_caiwenji", "Mbaby_sp_caoren", "Mbaby_sp_diaochan", "Mbaby_sp_jiangwei", "Mbaby_sp_jiaxu", "Mbaby_sp_kongrong", "Mbaby_sp_machao", "Mbaby_sp_menghuo", "Mbaby_sp_ol_zhanghe", "Mbaby_sp_pangde", "Mbaby_sp_sunshangxiang", "Mbaby_sp_taishici", "Mbaby_sp_xiahoushi", "Mbaby_sp_zhangliao", "Mbaby_sp_zhugeliang", "Mbaby_sunce", "Mbaby_sundeng", "Mbaby_sunhanhua", "Mbaby_sunhao", "Mbaby_sunliang", "Mbaby_sunluban", "Mbaby_sunluyu", "Mbaby_sunqian", "Mbaby_sunquan", "Mbaby_sunshangxiang", "Mbaby_sunwukong", "Mbaby_sunxiu", "Mbaby_tadun", "Mbaby_taishici", "Mbaby_tangji", "Mbaby_tunxingmenglix", "Mbaby_tw_mateng", "Mbaby_wangji", "Mbaby_wangping", "Mbaby_wangrong", "Mbaby_wangshuang", "Mbaby_wangtao", "Mbaby_wangyue", "Mbaby_wangyun", "Mbaby_weiwenzhugezhi", "Mbaby_weiyan", "Mbaby_wenqin", "Mbaby_wenyang", "Mbaby_wolongfengchu", "Mbaby_wuguotai", "Mbaby_wulan", "Mbaby_wutugu", "Mbaby_wuxian", "Mbaby_xf_yiji", "Mbaby_xiahouba", "Mbaby_xiahoudun", "Mbaby_xiahoulingnv", "Mbaby_xiahoushi", "Mbaby_xiahouyuan", "Mbaby_xianglang", "Mbaby_xiaoqiao", "Mbaby_xiaoshan", "Mbaby_xielingyu", "Mbaby_xinxianying", "Mbaby_xizhicai", "Mbaby_xuezong", "Mbaby_xugong", "Mbaby_xuhuang", "Mbaby_xunyou", "Mbaby_xunyu", "Mbaby_xushao", "Mbaby_xusheng", "Mbaby_xushi", "Mbaby_xushu", "Mbaby_xuyou", "Mbaby_xuzhu", "Mbaby_yanbaihu", "Mbaby_yanfuren", "Mbaby_yangwan", "Mbaby_yangxiu", "Mbaby_yanjun", "Mbaby_yanrou", "Mbaby_yanwen", "Mbaby_yanyan", "Mbaby_yinfuren", "Mbaby_yl_luzhi", "Mbaby_yuanshao", "Mbaby_yuanshu", "Mbaby_yuejin", "Mbaby_yufan", "Mbaby_yuji", "Mbaby_yujin", "Mbaby_zhangbao", "Mbaby_zhangchangpu", "Mbaby_zhangchunhua", "Mbaby_zhangfei", "Mbaby_zhangfen", "Mbaby_zhanggong", "Mbaby_zhanghe", "Mbaby_zhangji", "Mbaby_zhangjiao", "Mbaby_zhangliang", "Mbaby_zhangliao", "Mbaby_zhanglu", "Mbaby_zhangning", "Mbaby_zhangqiying", "Mbaby_zhangrang", "Mbaby_zhangwen", "Mbaby_zhangxingcai", "Mbaby_zhangxuan", "Mbaby_zhangyi", "Mbaby_zhangzhang", "Mbaby_zhaoang", "Mbaby_zhaotongzhaoguang", "Mbaby_zhaoxiang", "Mbaby_zhaoyun", "Mbaby_zhenghun", "Mbaby_zhenji", "Mbaby_zhonghui", "Mbaby_zhongyao", "Mbaby_zhoucang", "Mbaby_zhoufang", "Mbaby_zhoufei", "Mbaby_zhoutai", "Mbaby_zhouyu", "Mbaby_zhugedan", "Mbaby_zhugeguo", "Mbaby_zhugejin", "Mbaby_zhugeke", "Mbaby_zhugeliang", "Mbaby_zhugezhan", "Mbaby_zhuhuan", "Mbaby_zhujun", "Mbaby_zhupeilan", "Mbaby_zhurong", "Mbaby_zhuzhi", "Mbaby_zongyu", "Mbaby_zoushi", "Mbaby_zumao", "Mbaby_zuoci", "Mbabysp_daqiao", "Mbabysp_liubei", "Mbabysp_xiaoqiao", "Mbabysp_xuhuang", "Mbabysp_zhangfei", "Mbabysp_zhenji", "Mfight_huangzhong", "Mmiao_caifuren", "Mmiao_caiwenji", "Mmiao_caoying", "Mmiao_daqiao", "Mmiao_diaochan", "Mmiao_huangyueying", "Mmiao_lvlingqi", "Mmiao_sunshangxiang", "Mmiao_wangyi", "Mmiao_xiaoqiao", "Mmiao_zhangchunhua", "Mmiao_zhangxingcai", "Mmiao_zhenji", "Mmiao_zhurong", "Mnian_zhouyu", "ahuinan", "bailingyun", "baosanniang", "baoxin", "beimihu", "bianyue", "bol_sunluban", "bolx_jsp_guanyu", "boss_baihu", "boss_baijiwenyuan", "boss_baiwuchang", "boss_bianchengwang", "boss_bifang", "boss_caiwenji", "boss_caocao", "boss_chi", "boss_chiyuzhuque", "boss_chujiangwang", "boss_diaochan", "boss_dizangwang", "boss_dongzhuo", "boss_duanyuzhongda", "boss_dushiwang", "boss_fudibian", "boss_fuweizilong", "boss_gongshenyueying", "boss_guojia", "boss_heiwuchang", "boss_huangyueying", "boss_huatuo", "boss_hundun", "boss_huoshenzhurong", "boss_jiarenzidan", "boss_jileibaihu", "boss_jinshenrushou", "boss_juechenmiaocai", "boss_kumuyuanrang", "boss_liang", "boss_liedixuande", "boss_lieshiyazi", "boss_lingjiaxuanwu", "boss_liubei", "boss_luocha", "boss_lvbu2", "boss_lvbu3", "boss_mamian", "boss_mengpo", "boss_mingxingzhu", "boss_mo", "boss_mushengoumang", "boss_nianshou_baonu", "boss_nianshou_heti", "boss_nianshou_jingjue", "boss_nianshou_renxing", "boss_nianshou_ruizhi", "boss_niutou", "boss_pangtong", "boss_pingdengwang", "boss_qiaokuijunyi", "boss_qinglong", "boss_qinguangwang", "boss_qiongqi", "boss_shaohao", "boss_shihuosuanni", "boss_shuishengonggong", "boss_shuishenxuanming", "boss_shujing", "boss_songdiwang", "boss_sunce", "boss_taihao", "boss_taishanwang", "boss_taotie", "boss_taowu", "boss_tianhoukongming", "boss_tuntianchiwen", "boss_wang", "boss_wuguanwang", "boss_xiangliu", "boss_xuanwu", "boss_yandi", "boss_yanling", "boss_yanluowang", "boss_yecha", "boss_yihanyunchang", "boss_yingzhao", "boss_yuhuoshiyuan", "boss_yunpingqinglong", "boss_zhangchunhua", "boss_zhangjiao", "boss_zhenji", "boss_zhouyu", "boss_zhuanlunwang", "boss_zhuanxu", "boss_zhugeliang", "boss_zhuque", "boss_zhuyan", "boss_zhuyin", "boss_zuoci", "budugen", "bulianshi", "buzhi", "ca_guosi", "ca_lijue", "ca_lvbu", "ca_shen_lijueguosi", "ca_wangyun", "ca_zhangji", "caifuren", "caimao", "caimaozhangyun", "caiwenji", "caiyong", "caizhenji", "caoang", "caoanmin", "caobuxing", "caocao", "caochong", "caochun", "caohong", "caojie", "caopi", "caoren", "caorui", "caoshuang", "caosong", "caoteng", "caoxi", "caoxing", "caoxiu", "caoyi", "caoying", "caoyu", "caoyuan", "caozhang", "caozhen", "caozhi", "cenhun", "cheliji", "chendao", "chendeng", "chendong", "chengbing", "chenggongying", "chengji", "chengjichengcui", "chengong", "chengpu", "chengyu", "chenjiao", "chenlin", "chenqun", "chentai", "chezhou", "chunyuqiong", "clan_hanrong", "clan_hanshao", "clan_luji", "clan_lujing", "clan_wangchang", "clan_wangguang", "clan_wanghun", "clan_wangling", "clan_wanglun", "clan_wangmingshan", "clan_wangshen", "clan_wangyun", "clan_wuban", "clan_wukuang", "clan_wuqiao", "clan_wuyi", "clan_xuncai", "clan_xuncan", "clan_xunshu", "clan_xunshuang", "clan_xunyou", "clan_yangbiao", "clan_yangci", "clan_yangxiu", "clan_yangzhong", "clan_zhonghui", "clan_zhongyao", "clan_zhongyu", "cuimao", "cuiyan", "cx_majun", "daqiao", "daxiaoqiao", "db_wenyang", "dc_bulianshi", "dc_caiyang", "dc_caochun", "dc_caoshuang", "dc_caozhi", "dc_chenqun", "dc_daxiaoqiao", "dc_dongzhao", "dc_duyu", "dc_ganfuren", "dc_gaolan", "dc_gongsunzan", "dc_huanghao", "dc_huangquan", "dc_huangzu", "dc_huban", "dc_hujinding", "dc_huojun", "dc_jiangji", "dc_jiangqing", "dc_jiben", "dc_jikang", "dc_jiling", "dc_jsp_guanyu", "dc_kongrong", "dc_lifeng", "dc_lingcao", "dc_liru", "dc_liuli", "dc_liuyu", "dc_luotong", "dc_lvkuanglvxiang", "dc_mateng", "dc_mengda", "dc_mifuren", "dc_ruiji", "dc_sb_caoang", "dc_sb_caohong", "dc_sb_chengyu", "dc_sb_chenlin", "dc_sb_dianwei", "dc_sb_dongcheng", "dc_sb_guanping", "dc_sb_hucheer", "dc_sb_jushou", "dc_sb_liuxie", "dc_sb_lusu", "dc_sb_zhangxiu", "dc_sb_zhouyu", "dc_sb_zhugejin", "dc_shen_huatuo", "dc_shixie", "dc_sp_jiaxu", "dc_sp_machao", "dc_sp_menghuo", "dc_sp_zhurong", "dc_sunhanhua", "dc_sunquan", "dc_sunru", "dc_sunziliufang", "dc_tianfeng", "dc_wangchang", "dc_wangling", "dc_wangyun", "dc_wuban", "dc_wuzhi", "dc_xiahouba", "dc_xiahouxuan", "dc_xushu", "dc_yangbiao", "dc_yanghu", "dc_yuejiu", "dc_zhangmancheng", "dc_zhangren", "dc_zhangyì", "dc_zhaotongzhaoguang", "dc_zhaoyǎn", "dc_zhugejun", "dc_zhuling", "dengai", "dengzhi", "dengzhong", "dianwei", "diaochan", "dingfeng", "dingyuan", "dongbai", "dongcheng", "dongguiren", "dongtuna", "dongwan", "dongxie", "dongyun", "dongzhuo", "drag_caoren", "drag_guanping", "drag_guanyinping", "drag_guanyu", "drag_liaohua", "drag_luxun", "drag_lvchang", "drag_pangde", "drag_shendan", "drag_shenyi", "drag_xusheng", "drag_zhoucang", "duanjiong", "duanqiaoxiao", "duanwei", "dufuren", "duji", "dukui", "duosidawang", "duxi", "duyu", "fanchou", "fanjiangzhangda", "fanyufeng", "feiyao", "feiyi", "fengfang", "fengfangnv", "fengxi", "fj_peixiu", "friend_cuijun", "friend_pangtong", "friend_shitao", "fuhuanghou", "fuqian", "furong", "furongfuqian", "fuwan", "fx_baosanniang", "ganfuren", "ganfurenmifuren", "ganning", "gaogan", "gaolan", "gaoshun", "gaoxiang", "gexuan", "gongsundu", "gongsunkang", "gongsunxiu", "gongsunyuan", "gongsunzan", "guanhai", "guanlu", "guanping", "guanqiujian", "guansuo", "guanyinping", "guanyu", "guanyue", "guanzhang", "guohuai", "guohuanghou", "guojia", "guosi", "guotu", "guotufengji", "guoyuan", "guyong", "hanba", "handang", "hanfu", "hanhaoshihuan", "hanlong", "hanmeng", "hanshiwuhu", "hansui", "haomeng", "haopu", "haozhao", "hejin", "heqi", "hetaihou", "heyan", "hm_bairao", "hm_bocai", "hm_bosi", "hm_chengyuanzhi", "hm_dengmao", "hm_fuyun", "hm_gaosheng", "hm_guigu", "hm_heman", "hm_nanhualaoxian", "hm_shen_luzhi", "hm_shen_zhangbao", "hm_shen_zhangliang", "hm_tangzhou", "hm_taosheng", "hm_yanzheng", "hm_yudu", "houcheng", "hs_caohuan", "hs_liuxie", "hs_liuxuan", "hs_sunhao", "huaman", "huan_caoang", "huan_caochong", "huan_caopi", "huan_caozhi", "huan_dianwei", "huan_dingshangwan", "huan_guojia", "huan_huanggai", "huan_jiangwei", "huan_liufeng", "huan_liushan", "huan_luxun", "huan_simayi", "huan_weiyan", "huan_zhanghe", "huan_zhaoyun", "huan_zhugeguo", "huanfan", "huangfusong", "huanggai", "huanghao", "huangjinleishi", "huangyueying", "huangzu", "huatuo", "huaxin", "huaxiong", "hucheer", "hujinding", "huojun", "huzhao", "huzun", "jd_hanlong", "jd_jin_simashi", "jd_jin_simazhao", "jd_jin_wangyuanji", "jd_jin_xiahouhui", "jd_ol_huaxin", "jd_sb_caocao", "jd_sb_daqiao", "jd_sb_fazheng", "jd_sb_ganning", "jd_sb_guanyu", "jd_sb_huangyueying", "jd_sb_jiangwei", "jd_sb_liubei", "jd_sb_menghuo", "jd_sb_pangtong", "jd_sb_sp_zhugeliang", "jd_sb_sunshangxiang", "jd_sb_xiaoqiao", "jd_sb_xuhuang", "jd_sb_yuanshao", "jd_sb_yujin", "jd_sb_zhangfei", "jd_sb_zhaoyun", "jd_sp_yangwan", "jiachong", "jiakui", "jiangfei", "jianggan", "jiangji", "jiangqing", "jiangwei", "jiangziya", "jianyong", "jiaxu", "jikang", "jiling", "jimiaojimu", "jin_guohuai", "jin_jiachong", "jin_simashi", "jin_simayi", "jin_simazhao", "jin_wangyuanji", "jin_xiahouhui", "jin_yanghu", "jin_yanghuiyu", "jin_zhangchunhua", "jsp_caoren", "jsp_ganfuren", "jsp_guanyu", "jsp_huangyueying", "jsp_liubei", "jsp_zhaoyun", "jsrg_caofang", "jsrg_caojiewangfu", "jsrg_chendeng", "jsrg_chenfan", "jsrg_chunyuqiong", "jsrg_dengai", "jsrg_dongbai", "jsrg_dongzhuo", "jsrg_fanjiangzhangda", "jsrg_gaoxiang", "jsrg_guojia", "jsrg_guoxun", "jsrg_hansui", "jsrg_hejin", "jsrg_huangfusong", "jsrg_huangzhong", "jsrg_jiananfeng", "jsrg_jiangwei", "jsrg_kongrong", "jsrg_limi", "jsrg_liubiao", "jsrg_liuhong", "jsrg_liuyan", "jsrg_liuyong", "jsrg_lougui", "jsrg_lukang", "jsrg_luxun", "jsrg_lvbu", "jsrg_machao", "jsrg_malong", "jsrg_pangtong", "jsrg_qiaoxuan", "jsrg_simaliang", "jsrg_simayi", "jsrg_songhuanghou", "jsrg_sunce", "jsrg_sunjun", "jsrg_sunlubansunluyu", "jsrg_sunshangxiang", "jsrg_tufashujineng", "jsrg_wangjun", "jsrg_wangyun", "jsrg_weiwenzhugezhi", "jsrg_wenyang", "jsrg_xiahouen", "jsrg_xiahourong", "jsrg_xugong", "jsrg_yangbiao", "jsrg_yangqiu", "jsrg_yl_luzhi", "jsrg_yuanshao", "jsrg_zhangchu", "jsrg_zhangfei", "jsrg_zhanghe", "jsrg_zhanghuan", "jsrg_zhangjiao", "jsrg_zhangju", "jsrg_zhangliao", "jsrg_zhangren", "jsrg_zhangxuan", "jsrg_zhenji", "jsrg_zhugedan", "jsrg_zhujun", "jsrg_zoushi", "junk_lidian", "junk_sunquan", "junk_xuyou", "junk_zhangjiao", "junk_zhangrang", "jx_guanyu", "jx_shen_caoren", "jx_shen_liubiao", "jx_sunjian", "jx_zhouyu", "jy_caocao", "jy_caoren", "jy_huanggai", "jy_lusu", "jy_pangtong", "jy_zhangzhao", "jy_zhouyu", "jy_zhugeliang", "kaisa", "kanze", "kebineng", "kongrong", "kongshu", "kuailiangkuaiyue", "laimin", "laiyinger", "leibo", "leitong", "liangxing", "liaohua", "libai", "licaiwei", "lifeng", "lijue", "lingcao", "linghuyu", "lingju", "lingtong", "liqueguosi", "lisu", "litong", "liuba", "liubei", "liubian", "liubiao", "liuchen", "liucheng", "liuchongluojun", "liufeng", "liuhong", "liujinliupei", "liupan", "liupi", "liushan", "liuxie", "liuxiecaojie", "liuyan", "liuyao", "liuye", "liuyong", "liuyu", "liuzan", "liuzhang", "liwan", "liwei", "liyan", "liyi", "liyixiejing", "lizhaojiaobo", "longwang", "longyufei", "luji", "lukai", "lukang", "luotong", "luoxian", "lushi", "luxun", "luyusheng", "luzhi", "lvbu", "lvdai", "lvfan", "lvkai", "lvkuanglvxiang", "lvlingqi", "lvmeng", "lvqian", "machao", "macheng", "maliang", "malingli", "mamidi", "manchong", "mangyachang", "mateng", "matie", "mawan", "maxiumatie", "mayuanyi", "mayunlu", "mazhong", "mb_caoxing", "mb_chengui", "mb_ganfuren", "mb_guanyinping", "mb_huangzu", "mb_huban", "mb_jiachong", "mb_mengda", "mb_qinghegongzhu", "mb_simafu", "mb_simazhao", "mb_simazhou", "mb_sp_guanqiujian", "mb_sp_zhenji", "mb_sunjun", "mb_sunluyu", "mb_tianfeng", "mb_wangjing", "mb_wenqin", "mb_xiahoushang", "mb_xianglang", "mb_xingdaorong", "mb_xuezong", "mb_yanghong", "mb_zhangfen", "mb_zhangyan", "menghuo", "mengjie", "mengyou", "miheng", "mini_lvbu", "mini_lvmeng", "mini_zhugeliang", "minitaffy", "mizhu", "moqiongshu", "mortis", "mp_liuling", "mp_wangrong", "mp_xiangxiu", "muludawang", "mushun", "nanjixianweng", "nashime", "new_simayi", "new_yj_dongzhuo", "nezha", "niufu", "niujin", "ns_caoanmin", "ns_chendao", "ns_fanchou", "ns_jiaxu", "ns_lijue", "ns_zhangji", "ol_bianfuren", "ol_caifuren", "ol_caiwenji", "ol_caizhenji", "ol_caochong", "ol_caozhang", "ol_caozhi", "ol_chendeng", "ol_chengpu", "ol_chenlong", "ol_chouniu", "ol_dengai", "ol_dengzhi", "ol_dianwei", "ol_dingshangwan", "ol_dingyuan", "ol_dongxie", "ol_dongzhao", "ol_dongzhuo", "ol_fazheng", "ol_feiyi", "ol_fuhuanghou", "ol_furong", "ol_gaoshun", "ol_guanhai", "ol_guanzhang", "ol_guohuai", "ol_guozhao", "ol_haizhu", "ol_hanfu", "ol_huangzhong", "ol_huaxin", "ol_huban", "ol_hujinding", "ol_jiangwan", "ol_jiangwei", "ol_jianyong", "ol_jsrg_caocao", "ol_jsrg_liuhong", "ol_jsrg_zhaoyun", "ol_kebineng", "ol_liaohua", "ol_lifeng", "ol_lingtong", "ol_liru", "ol_lisu", "ol_liuba", "ol_liubiao", "ol_liupi", "ol_liushan", "ol_liuyan", "ol_liuyu", "ol_liuzhang", "ol_liwan", "ol_lukai", "ol_lusu", "ol_luyusheng", "ol_madai", "ol_maliang", "ol_maotu", "ol_mengda", "ol_nanhualaoxian", "ol_nianshou", "ol_niufu", "ol_pangde", "ol_pangtong", "ol_peixiu", "ol_peiyuanshao", "ol_pengyang", "ol_qianzhao", "ol_qiaoxuan", "ol_qinlang", "ol_sb_dengai", "ol_sb_dongzhuo", "ol_sb_gongsunzan", "ol_sb_guanyu", "ol_sb_huangyueying", "ol_sb_huaxiong", "ol_sb_jiangwei", "ol_sb_jushou", "ol_sb_kongrong", "ol_sb_pangtong", "ol_sb_sunjian", "ol_sb_taishici", "ol_sb_wenchou", "ol_sb_xiaoqiao", "ol_sb_yl_luzhi", "ol_sb_yuanshao", "ol_sb_yuanshu", "ol_sb_zhangfei", "ol_sb_zhangxiu", "ol_sb_zhaoyun", "ol_shen_dianwei", "ol_shenhou", "ol_sishe", "ol_sp_zhugeliang", "ol_sunjian", "ol_sunru", "ol_sunxiu", "ol_taoqian", "ol_tw_zhangji", "ol_wanglang", "ol_wangrong", "ol_wangyi", "ol_weiyan", "ol_weiyang", "ol_wuanguo", "ol_wuguotai", "ol_wujing", "ol_wuma", "ol_xiahouen", "ol_xiahouyuan", "ol_xiaoqiao", "ol_xinxianying", "ol_xuelingyun", "ol_xugou", "ol_xuhuang", "ol_yangfeng", "ol_yangfu", "ol_yangyi", "ol_yanwen", "ol_yinhu", "ol_youji", "ol_yuanhuan", "ol_yuanji", "ol_yuanshao", "ol_yuanshu", "ol_yufan", "ol_yujin", "ol_zhangchangpu", "ol_zhangchunhua", "ol_zhangliao", "ol_zhangmancheng", "ol_zhangrang", "ol_zhangyì", "ol_zhangzhang", "ol_zhaozhong", "ol_zhouqun", "ol_zhujun", "ol_zhuling", "ol_zhurong", "ol_zishu", "old_bulianshi", "old_caoren", "old_huangfusong", "old_huaxiong", "old_jiakui", "old_lingju", "old_machao", "old_madai", "old_quancong", "old_re_lidian", "old_yuanshu", "old_zhangqiying", "old_zhaoxiang", "old_zhoutai", "one_dc_sp_machao", "pangdegong", "pangfengyi", "pangshanmin", "pangtong", "pangxi", "panjun", "panzhangmazhong", "pe_jun_caocao", "pe_jun_liubei", "pe_jun_liuhong", "pe_jun_liushan", "pe_jun_liuxie", "pe_jun_sunce", "pe_jun_sunquan", "pe_jun_yuanshao", "pe_jun_zhangjiao", "pe_mengda", "pe_sunchen", "pe_wangyun", "pe_wenqin", "pe_zhonghui", "peixiu", "peiyuanshao", "pot_chendao", "pot_dongzhao", "pot_lougui", "pot_lusu", "pot_taishici", "pot_weiyan", "pot_yuji", "ps1059_guojia", "ps1062_zhouyu", "ps2063_zhaoyun", "ps2066_zhugeliang", "ps2067_zhaoyun", "ps2068_simayi", "ps2070_guojia", "ps2080_zhouyu", "ps_bilan", "ps_caocao", "ps_caopi", "ps_caozhi", "ps_duangui", "ps_gaowang", "ps_guanyu", "ps_guosheng", "ps_hankui", "ps_jiaxu", "ps_jin_simayi", "ps_lisong", "ps_liubei", "ps_lvbu", "ps_machao", "ps_simayi", "ps_sunquan", "ps_sunzhang", "ps_xiayun", "ps_zhangrang", "ps_zhaozhong", "ps_zhugeliang", "qianzhao", "qiaogong", "qiaorui", "qiaozhou", "qinghegongzhu", "qinlang", "qinmi", "qinyilu", "qiuliju", "qq_majun", "quancong", "quanhuijie", "quhuang", "quyi", "re_baosanniang", "re_bulianshi", "re_caifuren", "re_caiwenji", "re_caiyong", "re_caocao", "re_caochong", "re_caopi", "re_caorui", "re_caoxiu", "re_caozhang", "re_caozhen", "re_caozhi", "re_chendeng", "re_chengong", "re_chengpu", "re_chenqun", "re_chunyuqiong", "re_daqiao", "re_dengai", "re_dengzhi", "re_dianwei", "re_diaochan", "re_dongbai", "re_dongcheng", "re_dongzhuo", "re_duji", "re_fazheng", "re_fengfangnv", "re_fuhuanghou", "re_ganning", "re_gaoshun", "re_gongsunyuan", "re_gongsunzan", "re_guanping", "re_guanqiujian", "re_guanyu", "re_guanzhang", "re_guohuai", "re_guohuanghou", "re_guojia", "re_guotufengji", "re_guyong", "re_handang", "re_hanhaoshihuan", "re_hansui", "re_hejin", "re_heqi", "re_huanggai", "re_huangyueying", "re_huangzhong", "re_huatuo", "re_huaxiong", "re_hucheer", "re_jiangwei", "re_jianyong", "re_jiaxu", "re_jikang", "re_jsp_huangyueying", "re_jsp_pangtong", "re_jushou", "re_kanze", "re_liaohua", "re_lidian", "re_lingtong", "re_liru", "re_liubei", "re_liubiao", "re_liuchen", "re_liufeng", "re_liushan", "re_lusu", "re_luxun", "re_lvbu", "re_lvmeng", "re_machao", "re_madai", "re_maliang", "re_manchong", "re_masu", "re_mazhong", "re_menghuo", "re_miheng", "re_niujin", "re_panfeng", "re_pangde", "re_pangdegong", "re_pangtong", "re_panshu", "re_panzhangmazhong", "re_quancong", "re_quyi", "re_simalang", "re_simayi", "re_sp_taishici", "re_sp_zhugeliang", "re_sunben", "re_sunce", "re_sundeng", "re_sunjian", "re_sunluban", "re_sunluyu", "re_sunquan", "re_sunshangxiang", "re_sunxiu", "re_taishici", "re_taoqian", "re_wangyi", "re_wangyun", "re_weiwenzhugezhi", "re_weiyan", "re_wenpin", "re_wuguotai", "re_wuyi", "re_xiahoudun", "re_xiahoushi", "re_xiahouyuan", "re_xiaoqiao", "re_xinxianying", "re_xugong", "re_xuhuang", "re_xunchen", "re_xunyou", "re_xunyu", "re_xushu", "re_xuzhu", "re_yanwen", "re_yuanshao", "re_yuanshu", "re_yufan", "re_yuji", "re_zhangbao", "re_zhangchunhua", "re_zhangfei", "re_zhanggong", "re_zhanghe", "re_zhangjiao", "re_zhangliang", "re_zhangliao", "re_zhangsong", "re_zhangyi", "re_zhangzhang", "re_zhaoyun", "re_zhenji", "re_zhonghui", "re_zhongyao", "re_zhoucang", "re_zhouyu", "re_zhugedan", "re_zhugeliang", "re_zhuhuan", "re_zhuran", "re_zhurong", "re_zhuzhi", "re_zoushi", "re_zuoci", "ren_dengai", "ruanhui", "ruanji", "ruanyu", "ruiji", "sb_caocao", "sb_caopi", "sb_caoren", "sb_chengong", "sb_daqiao", "sb_diaochan", "sb_fazheng", "sb_ganning", "sb_gaoshun", "sb_gongsunzan", "sb_guanyu", "sb_guohuai", "sb_guojia", "sb_handang", "sb_huanggai", "sb_huangyueying", "sb_huangzhong", "sb_huaxiong", "sb_jiangwei", "sb_jiaxu", "sb_liubei", "sb_liubiao", "sb_luxun", "sb_lvbu", "sb_lvmeng", "sb_machao", "sb_menghuo", "sb_pangtong", "sb_sp_zhugeliang", "sb_sunce", "sb_sunquan", "sb_sunshangxiang", "sb_xiahoudun", "sb_xiahoushi", "sb_xiahouyuan", "sb_xiaoqiao", "sb_xuhuang", "sb_xunyu", "sb_yl_luzhi", "sb_yuanshao", "sb_yujin", "sb_zhangfei", "sb_zhanghe", "sb_zhangjiao", "sb_zhangliao", "sb_zhaoyun", "sb_zhenji", "sb_zhouyu", "sb_zhugejin", "sb_zhurong", "scl_caoying", "scl_luotong", "scl_pangdegong", "scl_peixiu", "scl_sunhanhua", "shamoke", "shen_caocao", "shen_caopi", "shen_diaochan", "shen_guanyu", "shen_huangzhong", "shen_huatuo", "shen_jiangwei", "shen_jiaxu", "shen_liubei", "shen_lusu", "shen_luxun", "shen_lvbu", "shen_lvmeng", "shen_pangtong", "shen_simayi", "shen_sunquan", "shen_taishici", "shen_xunyu", "shen_xuzhu", "shen_zhangfei", "shen_zhangliao", "shen_zhaoyun", "shen_zhenji", "shen_zhouyu", "shen_zhugeliang", "shengongbao", "shenpei", "shenxushao", "shibao", "shichangshi", "shixie", "shiyi", "simafu", "simalang", "simashi", "simayi", "simazhao", "simazhou", "sp_bianfuren", "sp_caiwenji", "sp_caoren", "sp_caosong", "sp_chendong", "sp_chenzhen", "sp_cuiyan", "sp_daqiao", "sp_diaochan", "sp_dongzhuo", "sp_fuhuanghou", "sp_fuwan", "sp_ganning", "sp_gaolan", "sp_gongsunzan", "sp_huaman", "sp_huangfusong", "sp_huaxin", "sp_jianggan", "sp_jiangqing", "sp_jiangwan", "sp_jiangwei", "sp_jiaxu", "sp_jiben", "sp_kongrong", "sp_liubei", "sp_liuqi", "sp_liuxie", "sp_lvfan", "sp_lvmeng", "sp_machao", "sp_maojie", "sp_menghuo", "sp_mifangfushiren", "sp_mifuren", "sp_mushun", "sp_ol_zhanghe", "sp_pangde", "sp_pangtong", "sp_pengyang", "sp_shenpei", "sp_simazhao", "sp_sufei", "sp_sunce", "sp_sunshangxiang", "sp_sunshao", "sp_taishici", "sp_wangcan", "sp_wangshuang", "sp_wangyuanji", "sp_xiahoudun", "sp_xinpi", "sp_xinxianying", "sp_xujing", "sp_xunchen", "sp_xuyou", "sp_yanghu", "sp_yangwan", "sp_zhangchangpu", "sp_zhangfei", "sp_zhanghe", "sp_zhangjiao", "sp_zhangliao", "sp_zhangwen", "sp_zhaoyun", "sp_zhugeliang", "sp_zhujun", "sp_zongyu", "star_dingfeng", "star_dongzhuo", "star_fazheng", "star_sunjian", "star_sunshangxiang", "star_wenchou", "star_xunyu", "star_yuanshao", "star_yuanshu", "star_zhangchunhua", "star_zhangrang", "star_zhangzhao", "std_chengpu", "std_chengyu", "std_db_wenyang", "std_dc_luotong", "std_dc_yanghu", "std_fanyufeng", "std_feiyi", "std_jianggan", "std_lijue", "std_lvlingqi", "std_mateng", "std_mayunlu", "std_panfeng", "std_re_dengzhi", "std_sunhao", "std_yuejin", "std_zhangyì", "std_zhouchu", "sunba", "sunce", "sundeng", "sunhanhua", "sunhao", "sunhong", "sunhuan", "sunjian", "sunlang", "sunli", "sunliang", "sunluban", "sunluyu", "sunqian", "sunquan", "sunru", "sunshangxiang", "sunshao", "sunsháo", "sunxiu", "sunyang", "sunyi", "sunyu", "sunziliufang", "sxrm_caopi", "sxrm_fuhuanghou", "sxrm_huatuo", "sxrm_jianggan", "sxrm_liubei", "sxrm_lvboshe", "sxrm_wanghou", "sxrm_xunyu", "sy_baosanniang", "tadun", "taffyold_ruiji", "taffyold_sb_zhugeliang", "taffyold_shen_xuzhu", "taipingsangong", "taishici", "tangji", "taoqian", "taoshen", "tengfanglan", "tenggongzhu", "tengyin", "tianchou", "tianfeng", "tianshangyi", "tianyu", "tongyuan", "tw_baoxin", "tw_beimihu", "tw_bianfuren", "tw_bingyuan", "tw_caoang", "tw_caocao", "tw_caohong", "tw_caoxiu", "tw_caozhao", "tw_chendong", "tw_chengpu", "tw_chenzhen", "tw_daxiaoqiao", "tw_dengzhi", "tw_dingfeng", "tw_fanchou", "tw_feiyi", "tw_fengxí", "tw_fuhuanghou", "tw_furong", "tw_fuwan", "tw_gexuan", "tw_gongsunfan", "tw_guanqiujian", "tw_guohuai", "tw_guyong", "tw_handang", "tw_haomeng", "tw_hejin", "tw_hucheer", "tw_huojun", "tw_jiangqing", "tw_jianshuo", "tw_jiling", "tw_jsp_guanyu", "tw_liufuren", "tw_liuhong", "tw_liuzhang", "tw_liwei", "tw_madai", "tw_maliang", "tw_mateng", "tw_mayunlu", "tw_mazhong", "tw_menghuo", "tw_niufudongxie", "tw_niujin", "tw_ol_sunjian", "tw_puyangxing", "tw_qiaogong", "tw_qiaorui", "tw_qiaozhou", "tw_re_caohong", "tw_re_fazheng", "tw_sb_caopi", "tw_sb_sp_zhugeliang", "tw_shen_guanyu", "tw_shen_lvmeng", "tw_simashi", "tw_sunluban", "tw_sunyi", "tw_tianyu", "tw_wangcan", "tw_wangchang", "tw_wangling", "tw_weixu", "tw_wenchou", "tw_wujing", "tw_xiahouba", "tw_xiahouen", "tw_xiahoushang", "tw_xuezong", "tw_xujing", "tw_xunchen", "tw_yangang", "tw_yangyi", "tw_yanliang", "tw_yanxiang", "tw_yj_zhanghe", "tw_yl_luzhi", "tw_yuantan", "tw_yufuluo", "tw_yujin", "tw_zangba", "tw_zhangfei", "tw_zhanghong", "tw_zhangji", "tw_zhangmancheng", "tw_zhangnan", "tw_zhangning", "tw_zhangyun", "tw_zhangzhao", "tw_zhaoxiang", "tw_zhouchu", "tw_zhugeguo", "tw_zhugejun", "tw_zhuzhi", "tw_zongyu", "tw_zumao", "two_dc_sp_machao", "ty_anying", "ty_anyingx", "ty_buzhi", "ty_chengjix", "ty_chenshi", "ty_fanjiang", "ty_fengxí", "ty_ganning", "ty_guanxing", "ty_guanyinping", "ty_guanyu", "ty_huangzhong", "ty_liaohua", "ty_liubei", "ty_liue", "ty_shamoke", "ty_shen_liubei", "ty_shicong", "ty_sunquan", "ty_tanxiong", "ty_wangque", "ty_wuban", "ty_wuque", "ty_yanque", "ty_zhangda", "ty_zhangnan", "ty_zhaorong", "v_caopi", "v_dongzhuo", "v_sunquan", "vtb_xiaojiu", "vtb_xiaole", "vtb_xiaosha", "vtb_xiaoshan", "vtb_xiaotao", "wangcan", "wangfuzhaolei", "wangguan", "wangji", "wangjun", "wangkuang", "wanglie", "wangling", "wangping", "wangrong", "wangshuang", "wangtao", "wangwei", "wangxiang", "wangyan", "wangyi", "wangyuanji", "wangyue", "wangyun", "wanniangongzhu", "wechat_baosanniang", "wechat_bianfuren", "wechat_buzhi", "wechat_caifuren", "wechat_caiwenji", "wechat_caiyong", "wechat_caizhenji", "wechat_caocao", "wechat_caochong", "wechat_caojie", "wechat_caopi", "wechat_caoren", "wechat_caoxiu", "wechat_caozhang", "wechat_caozhi", "wechat_chendeng", "wechat_ganfuren", "wechat_gaoshun", "wechat_gongsunyuan", "wechat_guansuo", "wechat_guanyinping", "wechat_guanyu", "wechat_guohuanghou", "wechat_guozhao", "wechat_guyong", "wechat_handang", "wechat_huanghao", "wechat_huangyueying", "wechat_huangzhong", "wechat_huaxiong", "wechat_huojun", "wechat_jianyong", "wechat_jiaxu", "wechat_jikang", "wechat_jsp_huangyueying", "wechat_kanze", "wechat_liaohua", "wechat_litong", "wechat_liubiao", "wechat_liuchen", "wechat_liucheng", "wechat_liuqi", "wechat_liuyan", "wechat_liuyao", "wechat_lizhaojiaobo", "wechat_lukang", "wechat_luxun", "wechat_lvmeng", "wechat_machao", "wechat_masu", "wechat_mayunlu", "wechat_menghuo", "wechat_old_zhaoxiang", "wechat_pangde", "wechat_pangdegong", "wechat_pangtong", "wechat_quancong", "wechat_re_gongsunzan", "wechat_re_luxun", "wechat_re_xushu", "wechat_re_yuanshu", "wechat_re_zuoci", "wechat_ruanhui", "wechat_sb_caocao", "wechat_sb_diaochan", "wechat_sb_guojia", "wechat_sb_huanggai", "wechat_sb_huangyueying", "wechat_sb_huangzhong", "wechat_sb_machao", "wechat_sb_sunce", "wechat_sb_sunshangxiang", "wechat_sb_zhangliao", "wechat_sb_zhaoyun", "wechat_shen_guanyu", "wechat_shen_lvbu", "wechat_shen_lvmeng", "wechat_shen_simayi", "wechat_shen_zhugeliang", "wechat_shenpei", "wechat_sp_caiwenji", "wechat_sp_diaochan", "wechat_sp_jiangwei", "wechat_sp_machao", "wechat_sp_pangde", "wechat_sp_taishici", "wechat_sp_wangcan", "wechat_sp_zhenji", "wechat_sp_zhugeliang", "wechat_sundeng", "wechat_sunhanhua", "wechat_sunhao", "wechat_sunliang", "wechat_sunluban", "wechat_sunluyu", "wechat_sunshangxiang", "wechat_taoqian", "wechat_wanglang", "wechat_wangping", "wechat_weiyan", "wechat_wuguotai", "wechat_xiahouba", "wechat_xiahoushi", "wechat_xiahouyuan", "wechat_xuezong", "wechat_xurong", "wechat_xusheng", "wechat_xushi", "wechat_xushu", "wechat_xuzhu", "wechat_yangxiu", "wechat_yanyan", "wechat_yj_ganning", "wechat_yj_huangzhong", "wechat_yj_jushou", "wechat_yj_weiyan", "wechat_yj_xuhuang", "wechat_yj_zhoubuyi", "wechat_yuanshao", "wechat_yufan", "wechat_zhangfei", "wechat_zhangxingcai", "wechat_zhangzhang", "wechat_zhaoxiang", "wechat_zhaoyun", "wechat_zhenji", "wechat_zhiyin_caiwenji", "wechat_zhiyin_caocao", "wechat_zhiyin_caopi", "wechat_zhiyin_caorui", "wechat_zhiyin_caozhi", "wechat_zhiyin_daqiao", "wechat_zhiyin_dianwei", "wechat_zhiyin_dongzhuo", "wechat_zhiyin_guanyu", "wechat_zhiyin_guohuanghou", "wechat_zhiyin_guojia", "wechat_zhiyin_hetaihou", "wechat_zhiyin_huangyueying", "wechat_zhiyin_jiangwei", "wechat_zhiyin_jiaxu", "wechat_zhiyin_kongrong", "wechat_zhiyin_liubei", "wechat_zhiyin_lusu", "wechat_zhiyin_luxun", "wechat_zhiyin_lvbu", "wechat_zhiyin_machao", "wechat_zhiyin_simayi", "wechat_zhiyin_sunce", "wechat_zhiyin_sunquan", "wechat_zhiyin_sunshangxiang", "wechat_zhiyin_wangyi", "wechat_zhiyin_xiaoqiao", "wechat_zhiyin_xinxianying", "wechat_zhiyin_xunyou", "wechat_zhiyin_xunyu", "wechat_zhiyin_xuzhu", "wechat_zhiyin_yuanshao", "wechat_zhiyin_zhangchunhua", "wechat_zhiyin_zhangfei", "wechat_zhiyin_zhaoyun", "wechat_zhiyin_zhenji", "wechat_zhiyin_zhouyu", "wechat_zhiyin_zhugeliang", "wechat_zhiyin_zhurong", "wechat_zhoutai", "wechat_zhugeguo", "wechat_zhuling", "wechat_zumao", "wechat_zuoci", "weiguan", "weiqing", "weiwenzhugezhi", "weizi", "wenpin", "wenyang", "wenyuan", "wn_caocao", "wn_chengyi", "wn_hansui", "wn_houxuan", "wn_shen_xuzhu", "wn_yangqiú", "wu_huangfusong", "wu_zhugeliang", "wuanguo", "wuban", "wufan", "wuguotai", "wujing", "wuke", "wulan", "wutugu", "wuxian", "wuyan", "wuyi", "xf_huangquan", "xf_sufei", "xf_tangzi", "xf_yiji", "xia_dianwei", "xia_guanyu", "xia_liubei", "xia_liyàn", "xia_lusu", "xia_shie", "xia_tongyuan", "xia_wangyue", "xia_xiahoudun", "xia_xiahousone", "xia_xiahouzie", "xia_xushu", "xia_yuzhenzi", "xia_zhangwei", "xia_zhaoe", "xiahouba", "xiahoudun", "xiahoujie", "xiahoulingnv", "xiahoumao", "xiahoushi", "xiahouxuan", "xiangchong", "xianglang", "xiaoqiao", "xiaoyuehankehan", "xielingyu", "xin_baosanniang", "xin_caifuren", "xin_caoxiu", "xin_caozhang", "xin_caozhen", "xin_chengpu", "xin_fazheng", "xin_fuhuanghou", "xin_gaoshun", "xin_gongsunzan", "xin_guohuai", "xin_guozhao", "xin_guyong", "xin_handang", "xin_hansui", "xin_huojun", "xin_jianyong", "xin_jushou", "xin_liaohua", "xin_liru", "xin_liubiao", "xin_mamidi", "xin_masu", "xin_panzhangmazhong", "xin_quancong", "xin_simayi", "xin_sunliang", "xin_sunluban", "xin_sunxiu", "xin_wuban", "xin_wuguotai", "xin_wuyi", "xin_xiahoudun", "xin_xusheng", "xin_xushu", "xin_yuanshao", "xin_yufan", "xin_yuji", "xin_zhangfei", "xin_zhangliang", "xin_zhangyi", "xin_zhonghui", "xin_zhoucang", "xin_zhoutai", "xin_zhuhuan", "xin_zhuran", "xin_zhuzhi", "xinchang", "xingdaorong", "xinpi", "xinping", "xinxianying", "xizheng", "xizhicai", "xj_peixiu", "xk_cuilian", "xk_luoli", "xk_penghu", "xk_pengqi", "xk_shanfu", "xk_zulang", "xuangongzhu", "xuezong", "xugong", "xujing", "xukun", "xunchen", "xunyou", "xunyu", "xunyuxunyou", "xurong", "xusheng", "xushi", "xuxin", "xuyou", "xuzhu", "yadan", "yanbaihu", "yanfuren", "yangfeng", "yangfu", "yanghong", "yanghuiyu", "yangwan", "yangxiu", "yangyan", "yangyi", "yangzhi", "yanjun", "yanpu", "yanrou", "yanwen", "yanxiang", "yanyan", "yeshiwen", "yinfuren", "yj_caoang", "yj_caocao", "yj_caohong", "yj_chezhou", "yj_dongzhuo", "yj_ehuan", "yj_ganning", "yj_huangzhong", "yj_jiaxu", "yj_jiling", "yj_jushou", "yj_liru", "yj_majun", "yj_qiaozhou", "yj_simafu", "yj_sufei", "yj_tianchuan", "yj_weiyan", "yj_xuangongzhu", "yj_xuhuang", "yj_xuyou", "yj_yongkai", "yj_zhangfei", "yj_zhanghe", "yj_zhangliao", "yj_zhenji", "yj_zhoubuyi", "yj_zhouji", "yl_luzhi", "yl_yuanshu", "yongjian_ganning", "yuanhuan", "yuanji", "yuanshaoyuanshu", "yuanshu", "yuantanyuanshang", "yuantanyuanxiyuanshang", "yue_daqiao", "yue_miheng", "yue_xiaoqiao", "yue_zhoufei", "yue_zhugeguo", "yuechen", "yuejin", "yuejiu", "yufan", "yujin", "yujin_yujin", "yy_caorui", "yy_gongsunyuan", "yy_gongsunzan", "yy_quancong", "yy_quyi", "yy_wenchou", "yy_yuanshao", "yy_zhaoyun", "zangba", "zhangbao", "zhangbu", "zhangchangpu", "zhangchu", "zhangchunhua", "zhangfei", "zhangfen", "zhanggong", "zhanghe", "zhangheng", "zhanghu", "zhanghua", "zhanghuai", "zhanghuyuechen", "zhangji", "zhangjinyun", "zhangkai", "zhangliang", "zhangliao", "zhangling", "zhanglu", "zhangmiao", "zhangning", "zhangqiying", "zhangrang", "zhangren", "zhangshiping", "zhangsong", "zhangwen", "zhangxingcai", "zhangxiu", "zhangxun", "zhangyan", "zhangyao", "zhangyi", "zhangyì", "zhangzhang", "zhangzhi", "zhangzhongjing", "zhaoang", "zhaotongzhaoguang", "zhaoxiang", "zhaoyan", "zhaoyun", "zhaoyǎn", "zhaozhi", "zhaozhong", "zhenghun", "zhengxuan", "zhenji", "zhonghui", "zhongyan", "zhongyao", "zhoucang", "zhouchu", "zhoufang", "zhoufei", "zhouqun", "zhoutai", "zhouyu", "zhugedan", "zhugeguo", "zhugejin", "zhugeke", "zhugeliang", "zhugemengxue", "zhugeruoxue", "zhugeshang", "zhugezhan", "zhuhuan", "zhujun", "zhuling", "zhupeilan", "zhuran", "zhurong", "zhutiexiong", "zhuzhi", "zongyu", "zumao", "zuoci", "zuofen"];
window.config = {
	extension_sources: {
		"GitHub Proxy": "https://mirror.ghproxy.com/https://raw.githubusercontent.com/libccy/noname-extension/master/",
		FastGit: "https://raw.fgit.cf/libccy/noname-extension/master/",
		GitHub: "https://raw.githubusercontent.com/libccy/noname-extension/master/",
	},
	extension_source: "GitHub Proxy",
	forbidai: ["ns_liuzhang"],
	forbidai_user: [],
	forbidall: [],
	forbidstone: ["zhugedan", "pal_xuanxiao", "hs_malfurion", "lusu", "chenlin", "hs_siwangzhiyi", "gjqt_bailitusu", "yuanshao", "swd_anka", "swd_nicole", "daqiao", "re_daqiao", "hs_xuanzhuanjijia", "zhuran", "huatuo", "swd_tuwei", "hs_guldan", "wangyi", "caoang", "swd_guyue", "swd_rongshuang", "swd_jiangziya", "guojia", "re_guojia", "shen_caocao", "swd_qiner", "caopi", "hs_yngvar", "guansuo", "gjqt_aruan", "swd_hanluo", "hs_anduin", "swd_huanglei", "yxs_yujix", "yxs_luzhishen", "swd_muyun", "ow_tianshi", "pal_yuejinzhao", "hs_antonidas", "xushi", "hs_lreno"],
	forbidchess: ["hetaihou", "swd_kangnalishi"],
	forbidboss: ["caiwenji", "gjqt_aruan", "pal_xuanxiao", "swd_hupo"],
	forbiddouble: ["zhugedan", "swd_kangnalishi", "dongzhuo", "wutugu", "zhangjian", "hs_siwangzhiyi", "hs_ronghejuren", "hs_shanlingjuren"],
	forbidthreecard: ["qiankunbiao", "shenhuofeiya", "gw_ciguhanshuang", "gw_birinongwu", "gw_qinpendayu", "gw_poxiao"],
	zhinang_tricks: ["guohe", "wuxie", "wuzhong", "dongzhuxianji"],
	connect_zhinang_tricks: ["guohe", "wuxie", "wuzhong", "dongzhuxianji"],
	all: {
		sgscharacters: ["standard", "shenhua", "refresh", "yijiang", "newjiang", "sixiang", "sp", "sp2", "xianding", "huicui", "extra", "old", "mobile", "shiji", "tw", "yingbian", "offline", "jsrg", "sxrm", "sb", "clan", "collab", "onlyOL"],
		sgscards: ["standard", "extra", "sp", "guozhan", "zhulu", "yingbian", "yongjian", "yunchou"],
		sgscharacters: ["standard", "shenhua", "refresh", "yijiang", "newjiang", "sixiang", "sp", "sp2", "xianding", "huicui", "extra", "old", "mobile", "shiji", "tw", "yingbian", "offline", "jsrg", "sxrm", "sb", "clan", "collab", "onlyOL"],
		sgscards: ["standard", "extra", "sp", "guozhan", "zhulu", "yingbian", "yongjian"],
		sgsmodes: ["identity", "guozhan", "versus", "doudizhu", "single", "brawl", "connect"],
		stockmode: ["identity", "guozhan", "versus", "boss", "doudizhu", "single", "chess", "stone", "connect", "brawl", "tafang"],
		stockextension: ["boss", "cardpile", "coin", "wuxing"],
		layout: ["default", "newlayout"],
		theme: ["woodden", "music", "simple"],
		card_font: ["xiaozhuan", "huangcao", "caoshu", "xingshu"],
		double_hp: ["hejiansan", "pingjun", "zuidazhi", "zuixiaozhi", "zonghe"],
		image_background_filter: ["default", "blur", "gray", "sepia", "invert", "saturate", "contrast", "hue", "brightness"],
	},

	game: "sgs",
	duration: 500,
	hoveration: 1000,
	doubleclick_intro: true,
	cheat: false,
	volumn_background: 8,
	volumn_audio: 8,

	connect_avatar: "caocao",
	connect_nickname: "无名玩家",
	config_menu: true,
	auto_popped_config: true,
	auto_popped_history: false,
	auto_skill: true,
	auto_confirm: true,
	enable_drag: true,
	enable_pressure: false,
	pressure_taptic: true,
	hover_handcard: true,
	hover_all: true,
	right_info: true,
	longpress_info: true,
	long_info: true,
	background_music: "music_default",
	background_audio: true,
	background_speak: true,
	glow_phase: "yellow",
	die_move: "flip",

	skin: {},
	gameRecord: {},
	extensionInfo: {},
	autoskilllist: [],
	hiddenModePack: [],
	hiddenCharacterPack: [],
	hiddenCardPack: [],
	hiddenPlayPack: [],
	hiddenBackgroundPack: [],
	customBackgroundPack: [],
	favouriteCharacter: [],
	favouriteMode: [],
	recentIP: [],
	brokenFile: [],

	theme: "simple",
	layout: "long2",
	card_style: "simple",
	cardback_style: "official",
	hp_style: "glass",

	image_character: "default",
	image_background: "人间安乐",

	asset_image: true,
	asset_font: true,

	card_font: "xiaozhuan",
	show_statusbar_ios: "off",
	show_statusbar_android: false,
	show_name: true,
	show_replay: false,
	show_round_menu: true,
	show_pause: true,
	show_auto: true,
	show_volumn: true,
	show_cardpile: true,
	only_fullskin: true,
	show_connect: true,
	show_wuxie: false,
	show_wuxie_self: true,
	show_stat: true,
	show_playerids: true,
	show_scrollbar: false,
	mousewheel: true,
	fold_card: true,
	threed_card: false,
	vertical_scroll: false,
	handcard_scroll: 0,
	animation: true,
	skill_animation_type: "default",
	paused: false,
	title: false,
	button_press: true,
	damage_shake: true,
	log_highlight: true,

	modeconfig: false,
	gameconfig: false,
	appearence: false,
	video: "20",
	coin: 0,

	intro: "i",
	right_click: "pause",
	sort: "type_sort",

	cards: ["standard", "extra"],
	characters: ["standard", "shenhua", "sp", "sp2", "yijiang", "newjiang", "refresh", "mobile", "extra", "yingbian", "sb", "tw", "offline", "clan", "collab", "xianding", "huicui", "shiji", "jsrg", "onlyOL", "taffy_character", "MiNikill", "WeChatkill", "sxrm"],
	moderned_chracters: ["standard", "shenhua", "sp", "sp2", "yijiang", "newjiang", "sixiang", "refresh", "mobile", "extra", "yingbian", "sb", "tw", "offline", "clan", "collab", "xianding", "huicui", "shiji", "onlyOL", "jsrg", "old", "diy", "ddd", "key", "sxrm"],
	connect_characters: ["diy", "ddd", "key", "old", "sixiang", "FaDongCharacter", "NianShouCharacter", "hezongkangqincharacter", "decadeQiHuan", "decadeZhuoGui", "decadeKuiBa", "HD_chaoshikong", "MX_feihongyinxue", "huodongcharacter"],
	connect_cards: ["huanlekapai", "guozhan", "sp", "zhulu", "yingbian", "yongjian", "xianxia", "yunchou"],
	plays: [],
	extensions: ["十周年UI", "挑战卡牌", "千幻聆音", "皮肤切换", "全能搜索", "永雏塔菲", "标记补充", "手杀MVP", "无名补丁", "指示线", "拖拽指示线", "补应变卡", "活动武将"],
	banned: [],
	bannedcards: [],
	forbidlist: [],
	bannedpile: {},
	customcardpile: {},
	addedpile: {},

	wuxie_self: false,
	update_link: "github",
	theme: "simple",
	player_height_nova: "long",
	card_style: "simple",
	cardback_style: "official",
	zhishixian: "Jinlong",
	equip_span: true,
	cardshape: "oblong",
	die_move: "off",
	show_rarity: true,
	show_cardpile_number: true,
	show_discardpile: true,
	forbidai_user: ["junko", "acetaffy", "taffyshen_duyu", "taffyshen_chengui", "taffyshendc_guanning", "taffyhuiwan_xushao", "taffyshen_shamoke", "taffyshen_yuji", "taffyhuiwan_sunquan", "taffyhuiwanplus_sunquan", "limulu", "taffyre_xuyou", "mutsumi", "mortis"],
	identity_bannedcards: ["muniu"],
	guozhan_bannedcards: ["muniu"],
	versus_bannedcards: ["muniu"],
	boss_bannedcards: ["muniu"],
	doudizhu_bannedcards: ["muniu"],
	single_bannedcards: ["muniu"],
	chess_bannedcards: ["muniu"],
	tafang_bannedcards: ["muniu"],
	stone_bannedcards: ["muniu"],
	connect_single_bannedcards: ["muniu"],
	connect_versus_bannedcards: ["muniu"],
	connect_guozhan_bannedcards: ["muniu"],
	connect_doudizhu_bannedcards: ["muniu"],
	connect_identity_bannedcards: ["muniu"],
	identity_banned: [...bannedList],
	guozhan_banned: [...bannedList],
	versus_banned: [...bannedList],
	boss_banned: [...bannedList],
	doudizhu_banned: [...bannedList],
	single_banned: [...bannedList],
	chess_banned: [...bannedList],
	tafang_banned: [...bannedList],
	stone_banned: [...bannedList],
	connect_single_banned: [...bannedList],
	connect_versus_banned: [...bannedList],
	connect_guozhan_banned: [...bannedList],
	connect_doudizhu_banned: [...bannedList],
	connect_identity_banned: [...bannedList],
	extension_永雏塔菲_enable: true,
	extension_挑战卡牌_enable: false,
	extension_全能搜索_enable: true,
	extension_补应变卡_enable: true,
	extension_手杀MVP_enable: true,
	extension_手杀MVP_yangshi: "on",
	extension_指示线_enable: true,
	extension_指示线_zhishixian: "jingdian",
	extension_拖拽指示线_enable: true,
	extension_无名补丁_enable: true,
	extension_无名补丁_xindmenu: "off",
	extension_无名补丁_xindchoose: "off",
	extension_无名补丁_xindsingle: false,
	extension_标记补充_enable: true,
	extension_标记补充_jinengxiugai: false,
	extension_标记补充_biaojixiugai: false,
	extension_标记补充_xunizhuangbeipai: false,
	extension_标记补充_zhijiechifa: false,
	extension_标记补充_shoushajishatexiao: true,
	extension_标记补充_jishatexiao: "shousha",
	extension_标记补充_youxishengfu: "identity",
	extension_标记补充_daojianfu: "dao",
	extension_标记补充_ervermaihua: false,
	extension_活动武将_enable: true,
	extension_活动武将_ShenZhangJiao: false,
	extension_活动武将_HDfightAudio: "off",
	extension_活动武将_HDskillAnimateAudio: false,
	extension_活动武将_ShowSeatNum: false,
	extension_皮肤切换_enable: true,
	extension_皮肤切换_showEditMenu: true,
	extension_皮肤切换_showPreviewDynamicMenu: true,
	extension_皮肤切换_hideHuanFu: true,
	extension_皮肤切换_isAttackFlipX: true,
	extension_皮肤切换_cugDynamicBg: true,
	extension_皮肤切换_clickPlayerDynamic: false,
	extension_皮肤切换_showTopArc: false,
	extension_十周年UI_enable: true,
	extension_十周年UI_cardPrettify: "png",
	extension_十周年UI_jiaohuyinxiao: true,
	extension_十周年UI_dynamicBackground: "off",
	extension_十周年UI_dynamicSkin: true,
	extension_十周年UI_dynamicSkin_dieAfter: false,
	extension_十周年UI_showTemp: true,
	extension_十周年UI_wujiangbeijing: true,
	extension_十周年UI_borderLevel: "four",
	extension_十周年UI_foldCardMinWidth: "45",
	extension_十周年UI_playerMarkStyle: "yellow",
	extension_十周年UI_newDecadeStyle: "othersOff",
	extension_十周年UI_shadowStyle: "off",
	extension_十周年UI_longLevel: "five",
	extension_十周年UI_loadingStyle: "othersOn",
	extension_十周年UI_GTBB: true,
	extension_十周年UI_XPJ: "off",
	extension_十周年UI_jindutiao: false,
	extension_十周年UI_JDTS: false,
	extension_千幻聆音_enable: true,
	qhly_currentViewSkin: "shousha",
	extension_千幻聆音_qhly_currentViewSkin: "shousha",
	qhly_replaceCharacterCard2: "nonereplace",
	extension_千幻聆音_qhly_replaceCharacterCard2: "nonereplace",
	qhly_nolihuiOrigin: true,
	extension_千幻聆音_qhly_nolihuiOrigin: true,
	qhly_smallwindowstyle: "shousha",
	extension_千幻聆音_qhly_smallwindowstyle: "shousha",
	qhly_originSkinPath: "image/skin/",
	extension_千幻聆音_qhly_originSkinPath: "image/skin/",
	qhly_skinconfig: true,
	extension_千幻聆音_qhly_skinconfig: true,
	qhly_noSkin: "origin",
	extension_千幻聆音_qhly_noSkin: "origin",
	qhly_decadeDynamic: "none",
	extension_千幻聆音_qhly_decadeDynamic: "none",
	qhly_skinset: {
		skin: {
			acetaffy: "3.jpg",
			bianxi: "夺关袭寨.jpg",
			ca_shen_caocao: "雄吞天下.jpg",
			ca_shen_wangyun: "文和乱武.jpg",
			caohua: "彩蝶恋花.jpg",
			caojinyu: "瓷语青花.jpg",
			caomao: "经典形象2.jpg",
			caoxian: "元春呈祥.jpg",
			caoxiancaohua: "锦瑟良缘.jpg",
			chengui: "战场荣耀.jpg",
			clan_wuxian: "芳泽沐鲤.jpg",
			clan_xunchen: "栖木之择.jpg",
			clan_zhongyan: "雪荣钟情.jpg",
			db_wenyang: "破云翔宇魏.jpg",
			dc_caocao: "雄吞天下.jpg",
			dc_guansuo: "龙战玄黄.jpg",
			dc_huangwudie: "云螭献瑞.jpg",
			dc_jiachong: "妄锋斩龙.jpg",
			dc_liubei: "逐鹿天下.jpg",
			dc_liuye: "焚焰天征.jpg",
			dc_qinghegongzhu: "清雅趣逗.jpg",
			dc_sb_guojia: "以身证道.jpg",
			dc_sb_huanggai: "以身证道.jpg",
			dc_sb_simayi: "隐龙如晦.jpg",
			dc_simashi: "目痛欲狂.jpg",
			dc_sunce: "傲凌绝顶2.jpg",
			dc_tengfanglan: "皓露沁兰.jpg",
			dc_wuyi: "骁勇金衔.jpg",
			dc_xujing: "丹枫盈瞳.jpg",
			dc_zhaoxiang: "月痕芳影.jpg",
			dc_zhaoyun: "龙腾虎跃.jpg",
			dc_zhouxuān: "枕梦南柯.jpg",
			dingshangwan: "夜阑扰梦.jpg",
			dm_simayi: "傲睨九州.jpg",
			drag_guansuo: "龙战玄黄1.jpg",
			guanning: "墨韵荷香.jpg",
			guozhao: "瓷语青花.jpg",
			himari: "动态经典.jpg",
			hm_shen_huangfusong: "奋钺振旅.jpg",
			hm_shen_yl_luzhi: "抒墨谏策.jpg",
			huangchengyan: "夜占吉凶.jpg",
			jd_sb_sunquan: "永开吴祚.jpg",
			jin_zhouchu: "义除三害.jpg",
			jsrg_caocao: "逐鹿天下.jpg",
			jsrg_guanyu: "以身证道.jpg",
			jsrg_guozhao: "瓷语青花.jpg",
			jsrg_liubei: "阑珊灯火.jpg",
			jsrg_nanhualaoxian: "野鹤闲云.jpg",
			jsrg_simazhao: "昭威淮南.jpg",
			jsrg_sunjian: "武烈开疆.jpg",
			jsrg_xushao: "声名鹊起.jpg",
			jsrg_xuyou: "附势而为2.jpg",
			jsrg_zhaoyun: "战宇龙腾.jpg",
			jsrg_zhugeliang: "经典形象2.jpg",
			luyi: "姝丽风华.jpg",
			majun: "能工巧匠.jpg",
			mb_caomao: "经典形象2.jpg",
			mb_luyusheng: "战场绝版.jpg",
			nanhualaoxian: "冠绝天下.jpg",
			ol_puyuan: "百战神机.jpg",
			ol_sb_zhangrang: "只手遮天.jpg",
			ol_xunyu: "书剑定远.jpg",
			panshu: "江东锦绣.jpg",
			pe_jun_caopi: "气荡山河.jpg",
			pk_sp_duyu: "弼朝博虬.jpg",
			ps_shen_machao: "迅骛惊雷.jpg",
			puyuan: "战场绝版.jpg",
			re_liuzan: "灵魂歌王.jpg",
			re_nanhualaoxian: "丰年映雪.jpg",
			re_sunyi: "腾龙翻江.jpg",
			re_xusheng: "破军杀将.jpg",
			scl_miheng: "击鼓骂曹.jpg",
			she_lvmeng: "剑起惊澜.jpg",
			shen_dengai: "巨灵撼宇.jpg",
			shen_ganning: "战破无间.jpg",
			shen_guojia: "倚星折月.jpg",
			shen_machao: "迅骛惊雷.jpg",
			shen_sunce: "霸王再世.jpg",
			shen_zhangjiao: "驭道震泽.jpg",
			shi_cenhun: "铁锁封江.jpg",
			simahui: "教诲不倦.jpg",
			sp_duyu: "弼朝博虬.jpg",
			sp_ol_caocao: "逐鹿天下.jpg",
			sp_ol_liubei: "阑珊灯火.jpg",
			sp_xiahoushi: "明良千古.jpg",
			sp_zhenji: "芳菲栉雨.jpg",
			star_caoren: "国之柱石.jpg",
			sunlingluan: "鸾心初动.jpg",
			swimsuit_hoshino: "动态经典.jpg",
			taffydc_guanning: "墨韵荷香.jpg",
			taffydc_xushao: "战场荣耀.jpg",
			taffyhuiwan_xushao: "评世雕龙.jpg",
			taffymb_shen_caocao: "四方归心.jpg",
			taffyold_baby_shen_simayi: "鉴往知来.jpg",
			taffyold_bailingyun: "粽香馥郁.jpg",
			taffyold_clan_xuncai: "雅柔映采.jpg",
			taffyold_clan_yangxiu: "葳蕤溯风.jpg",
			taffyold_clan_zhonghui: "潜蛟觊天1.jpg",
			taffyold_db_wenyang: "破云翔宇魏.jpg",
			taffyold_dc_shen_huatuo: "五灵济世.jpg",
			taffyold_dc_zhaoyǎn: "遐迩一体.jpg",
			taffyold_fuqian: "与贼决死.jpg",
			taffyold_lukai: "雷骁斥遒.jpg",
			taffyold_new_simayi: "鉴往知来.jpg",
			taffyold_new_yj_dongzhuo: "踞京问鼎.jpg",
			taffyold_ol_feiyi: "安民护祚.jpg",
			taffyold_ol_hujinding: "金粉福颜.jpg",
			taffyold_ol_luyusheng: "战场绝版.jpg",
			taffyold_ol_nanhualaoxian: "着墨山河.jpg",
			taffyold_ol_sb_dongzhuo: "踞京问鼎2.jpg",
			taffyold_ol_sb_guanyu: "以身证道.jpg",
			taffyold_ol_sb_yl_luzhi: "抒墨谏策.jpg",
			taffyold_ruanyu: "墨卷浩瀚.jpg",
			taffyold_sb_caopi: "气荡山河.jpg",
			taffyold_sb_guanyu: "以身证道.jpg",
			taffyold_sb_huanggai: "以身证道.jpg",
			taffyold_sb_huangzhong: "烈箭贯云.jpg",
			taffyold_sb_sp_zhugeliang: "龙跃凤鸣.jpg",
			taffyold_sb_zhugeliang: "国之柱石.jpg",
			taffyold_scs_bilan: "朝华同袍.jpg",
			taffyold_scs_duangui: "朝华同袍.jpg",
			taffyold_scs_gaowang: "朝华同袍.jpg",
			taffyold_scs_guosheng: "朝华同袍.jpg",
			taffyold_scs_hankui: "朝华同袍.jpg",
			taffyold_scs_lisong: "朝华同袍.jpg",
			taffyold_scs_sunzhang: "朝华同袍.jpg",
			taffyold_scs_xiayun: "朝华同袍.jpg",
			taffyold_scs_zhangrang: "朝华同袍.jpg",
			taffyold_scs_zhaozhong: "朝华同袍.jpg",
			taffyold_shen_lusu: "青牛化圣.jpg",
			taffyold_shen_pangtong: "臻华福天.jpg",
			taffyold_shen_xunyu: "匡汉延祚.jpg",
			taffyold_tengfanglan: "脂车香姝.jpg",
			taffyold_tenggongzhu: "菡萏慕卿.jpg",
			taffyold_tw_shen_lvmeng: "兼资文武.jpg",
			taffyold_v_sunquan: "永开吴祚.jpg",
			taffyold_xin_guozhao: "阙寒惊凤.jpg",
			taffyold_xin_simayi: "鉴往知来.jpg",
			taffyold_xurong: "怒燎横空.jpg",
			taffyold_yj_majun: "能工巧匠.jpg",
			taffyold_yuantanyuanshang: "常棣失华.jpg",
			taffyold_zhangrang: "只手遮天.jpg",
			taffype_guozhao: "瓷语青花.jpg",
			taffyps_shen_jiangwei: "炽剑补天.jpg",
			taffyre_shamoke: "骁勇金衔.jpg",
			taffyre_xushao: "评世雕龙.jpg",
			taffyre_xuyou: "附势而为.jpg",
			taffyred_xin_jushou: "落定天元.jpg",
			taffyshen_duyu: "弼朝博虬2.jpg",
			taffyshen_shamoke: "骁勇金衔.jpg",
			taffyshen_xushao: "评世雕龙.jpg",
			taffyshen_yuji: "虚拟天团.jpg",
			ty_luxun: "烈火烛天.jpg",
			ty_shen_guanyu: "血海罗刹.jpg",
			ty_shen_zhangfei: "傲睨山河.jpg",
			v_zhangliao: "龙生九子.jpg",
			wanglang: "骧龙御宇.jpg",
			wn_shen_machao: "星夜袭曹.jpg",
			wolongfengchu: "凤宇龙翔.jpg",
			xin_lingtong: "转战回击.jpg",
			xuelingyun: "金蛟巧刻.jpg",
			xushao: "声名鹊起.jpg",
			yangbiao: "国之柱石.jpg",
			yj_zhonghui: "潜蛟觊天2.jpg",
			yue_caiwenji: "以身证道.jpg",
			yue_diaochan: "舞惑群心.jpg",
			yue_zhouyu: "运筹帷幄.jpg",
			yy_simayi: "重张区宇.jpg",
			zerong: "一念佛魔.jpg",
			zhangxuan: "涟漪夏梦.jpg",
			zhoubuyi: "云上拾逸.jpg",
			zhoushan: "骁勇金衔.jpg",
			zhouyi: "金甲破阵.jpg",
			zhujianping: "命镜幻生.jpg",
			zombie_jiaxu: "荡然由心.jpg",
		},
		skinAudioList: {},
		audioReplace: {},
	},

	mode: "identity",
	mode_config: {
		global: {
			player_number: 8,
			auto_identity: "off",
			double_character: false,
			save_progress: true,
			free_choose: true,
			swap: true,
			change_identity: true,
			battle_number: 3,
			double_hp: "pingjun",
		},
		identity: {
			identity: [
				["zhu", "fan"],
				["zhu", "nei", "fan"],
				["zhu", "zhong", "nei", "fan"],
				["zhu", "zhong", "nei", "fan", "fan"],
				["zhu", "zhong", "nei", "fan", "fan", "fan"],
				["zhu", "zhong", "zhong", "nei", "fan", "fan", "fan"],
				["zhu", "zhong", "zhong", "nei", "fan", "fan", "fan", "fan"],
				["zhu", "zhong", "zhong", "zhong", "nei", "fan", "fan", "fan", "fan"],
				["zhu", "zhong", "zhong", "zhong", "nei", "nei", "fan", "fan", "fan", "fan"],
			],
			choice: {
				zhu: 3,
				zhong: 4,
				nei: 5,
				fan: 3,
			},
			show_identity: true,
			difficulty: "normal",
			dierestart: true,
			connect_change_card: true,
			connect_enhance_zhu: "off",
			auto_mark_identity: false,
			enhance_zhu: "off",
			change_card: "unlimited",
			continue_game: true,
			revive: true,
		},
		guozhan: {
			difficulty: "normal",
			initshow_draw: "mark",
			dierestart: true,
		},
		versus: {
			connect_versus_mode: "2v2",
			connect_olfeiyang_four: false,
			versus_mode: "two",
			olfeiyang_four: false,
		},
		boss: {
			single_control: false,
		},
		doudizhu: {
			connect_change_card: true,
			change_card: "unlimited",
			continue_game: true,
			revive: true,
		},
		single: {
			connect_single_mode: "dianjiang",
			connect_change_card: true,
			single_mode: "dianjiang",
			change_card: "unlimited",
		},
	},
	current_mode: {},
	customforbid: [],
	forbid: [
		["huashen"],
		["rehuashen"],
		["xinmanjuan"],
		//['xinleiji','fuji'],
		["xinleiji", "xinfu_jijun"],
		["reluanji", "jueqing"],
		["lianying", "rende"],
		["lianying", "anxian"],
		["lianying", "yinguo"],
		["lianying", "qingjian"],
		["boss_juejing", "rende"],
		["boss_juejing", "anxian"],
		["boss_juejing", "yinguo"],
		["boss_juejing", "qingjian"],
		["shangshi", "rende"],
		["shangshi", "anxian"],
		["shangshi", "yinguo"],
		["shangshi", "qingjian"],
		["rende", "relianying"],
		["anxian", "relianying"],
		["yinguo", "relianying"],
		["shenxing", "relianying"],
		["qingjian", "relianying"],
		["rende", "yuling"],
		["anxian", "yuling"],
		["yinguo", "yuling"],
		["qingjian", "yuling"],
		//['qingnang','yiji'],
		//['qingnang','reyiji'],
		//['qingjian','tuntian'],
		// ['yiji','tuntian'],
		// ['reyiji','tuntian'],
		["tuntian", "guidao"],
		["tuntian", "tiandao"],
		["tuntian", "huanshi"],
		// ['tuntian','guicai'],
		// ['jiang','chongzhen'],
		// ['fenji','yuling'],
		["jiushi", "guixin"],
		["xiuhua", "xuanfeng"],
		["xiuhua", "duanxing"],
		["xiuhua", "xiaoji"],
		["xiuhua", "xiaoji"],
		// ['jiushi','jushou'],
		// ['jiushi','kuiwei'],
		["zishu", "xinfu_songsang"],
		["zishu", "shenxing"],
		["minishendao", "luoshen"],
		["minishendao", "reluoshen"],
		["akane_quanqing", "lianying"],
		["akane_quanqing", "relianying"],
		["akane_quanqing", "shangshi"],
		["dcruyi", "cxliushi"],
	],
};
bannedList = null;
