const characters = {
	taffyboss_xushao: ["male", "shen", 4, ["taffyboss_pingjian"], ["qun", "boss", "bossallowed"], "qun"],
	taffyold_wu_zhugeliang: ["male", "shu", "4/7", ["dcjincui", "taffyold_dcqingshi", "taffyold_dczhizhe"], ["name:诸葛|亮", "character:wu_zhugeliang", "die:wu_zhugeliang"]],
	taffydc_guanning: ["male", "qun", "3/7", ["taffydc_dunshi"]],
	acetaffy: ["female", "shen", 3, ["taffybaomi", "taffyfeizhu", "taffyzuoai", "taffychusheng"], ["name:永雏|塔菲", "qun"]],
	minitaffy: ["female", "qun", 1, ["taffytangshi", "taffyzisha"], ["name:永雏|塔菲"]],
	taffydc_xushao: ["male", "qun", 4, ["taffydc_pingjian"]],
	taffyhuiwan_xushao: ["male", "shen", 1, ["taffyhuiwan_pingjian"], ["qun"]],
	taffyold_tw_niufudongxie: ["double", "qun", 4, ["taffyold_twjuntun", "taffyold_twxiongxi", "taffyold_twxiafeng"], ["name:牛|辅-董|翓", "character:tw_niufudongxie", "die:tw_niufudongxie"]],
	taffyold_tw_zhangmancheng: ["male", "qun", 4, ["twfengji", "twyiju", "taffyold_twbudao"], ["character:tw_zhangmancheng", "die:tw_zhangmancheng"]],
	taffyshen_yuji: ["male", "shen", 3, ["taffyshen_guhuo"], ["qun"]],
	junko: ["female", "shen", 3, ["junkochunhua", "junkokuangqi", "junkowuming"], ["qun"]],
	taffyhuiwan_sunquan: ["male", "wu", 4, ["rezhiheng", "rejiuyuan", "huiwan"]],
	taffyhuiwanplus_sunquan: ["male", "wu", 4, ["rezhiheng", "rejiuyuan", "huiwanplus"]],
	taffymb_shen_caocao: ["male", "shen", 3, ["guixin", "feiying"], ["wei", "character:shen_caocao", "die:shen_caocao"]],
	taffyold_baby_shen_simayi: ["male", "shen", 3, ["taffyold_baby_renjie", "taffyold_baby_jilue", "lianpo"], ["wei", "name:司马|懿"]],
	taffyshen_duyu: ["male", "shen", 5, ["taffyshen_miewu"], ["qun"]],
	taffyshen_chengui: ["male", "shen", 3, ["taffyshen_dcyingtu", "taffyshen_dccongshi"], ["qun"]],
	taffyold_ruiji: ["female", "wu", 3, ["taffyold_qiaoli", "taffyold_qingliang"], ["name:芮|null", "character:ruiji", "die:ruiji"]],
	taffyold_tengfanglan: ["female", "wu", 3, ["taffyold_luochong", "taffyold_aichen"], ["character:tengfanglan", "die:tengfanglan"]],
	taffyold_ol_feiyi: ["male", "shu", 3, ["taffyold_yanru", "taffyold_hezhong"], ["character:ol_feiyi", "die:ol_feiyi"]],
	taffyshendc_guanning: ["male", "shen", "3/7", ["taffyshendc_dunshi"], ["qun"]],
	taffyre_xushao: ["male", "qun", 3, ["taffyre_pingjian"]],
	taffyold_sb_caopi: ["male", "wei", 3, ["taffyold_sbxingshang", "taffyold_sbfangzhu", "taffyold_sbsongwei"], ["zhu", "character:sb_caopi", "die:sb_caopi"]],
	taffyold_yuantanyuanshang: ["male", "qun", 4, ["taffyold_neifa"], ["name:袁|谭-袁|尚", "character:yuantanyuanshang", "die:yuantanyuanshang"]],
	taffyold_zhanghua: ["male", "jin", 3, ["olbihun", "olchuanwu", "oljianhe"], ["character:zhanghua", "die:zhanghua"]],
	taffyold_ol_pengyang: ["male", "shu", 3, ["taffyold_olxiaofan", "taffyold_oltuishi", "nzry_cunmu"], ["tempname:ol_pengyang", "character:ol_pengyang", "die:ol_pengyang"]],
	taffyold_sb_sp_zhugeliang: ["male", "shu", 3, ["taffyold_sbhuoji", "taffyold_sbkanpo"], ["name:诸葛|亮", "character:sb_sp_zhugeliang", "die:sb_sp_zhugeliang"]],
	taffyold_sb_zhugeliang: ["male", "shu", 3, ["taffyold_sbguanxing", "taffyold_sbkongcheng"], ["name:诸葛|亮", "character:sb_zhugeliang", "die:sb_zhugeliang"]],
	taffyold_sb_guanyu: ["male", "shu", 4, ["taffyold_sbwusheng", "taffyold_sbyijue"], ["character:sb_guanyu", "die:sb_guanyu"]],
	taffyold_bailingyun: ["female", "wei", 3, ["taffyold_dclinghui", "dcxiace", "dcyuxin"], ["character:bailingyun", "die:bailingyun"]],
	taffyold_clan_zhonghui: ["male", "wei", "3/4", ["taffyold_clanyuzhi", "taffyold_clanxieshu", "clanbaozu"], ["clan:颍川钟氏", "character:clan_zhonghui", "die:clan_zhonghui"]],
	taffyold_ol_luyusheng: ["female", "wu", 3, ["taffyold_olcangxin", "olrunwei"], ["character:ol_luyusheng", "die:ol_luyusheng"]],
	taffyold_shen_lusu: ["male", "shen", 3, ["taffyold_tamo", "taffyold_dingzhou", "taffyold_zhimeng"], ["wu", "character:shen_lusu", "die:shen_lusu"]],
	taffyold_wu_guanyu: ["male", "shu", 4, ["taffyold_dcjuewu", "taffyold_dcwuyou", "taffyold_dcyixian"], ["character:wu_guanyu", "die:wu_guanyu"]],
	taffyold_dc_shen_huatuo: ["male", "shen", 3, ["taffyold_jingyu", "taffyold_lvxin", "huandao"], ["qun", "character:dc_shen_huatuo", "die:dc_shen_huatuo"]],
	taffyold_shen_xuzhu: ["male", "shen", 5, ["taffyold_zhengqing", "zhuangpo"], ["wei", "character:shen_xuzhu", "die:shen_xuzhu"]],
	taffyshen_xushao: ["male", "shen", 3, ["taffyshen_pingjian"], ["qun"]],
	taffyold_tenggongzhu: ["female", "wu", 4, ["taffyold_xingchong", "taffyold_liunian"], ["name:孙|null", "character:tenggongzhu", "die:tenggongzhu"]],
	swimsuit_hoshino: ["female", "shen", 3, ["hoshino_shuiyuan", "hoshino_shuiji", "hoshino_naishu", "hoshino_haile"], ["qun", "name:小鸟游|星野"]],
	limulu: ["male", "shen", 3, ["limulu_baoshi", "limulu_zhihui", "limulu_mowang"], ["qun"]],
	taffyold_tw_baoxin: ["male", "qun", 4, ["taffyold_twmutao", "taffyold_twyimou"], ["character:tw_baoxin", "die:tw_baoxin"]],
	taffyold_shichangshi: ["male", "qun", 1, ["taffyold_mbdanggu", "taffyold_mbmowang"], ["sex:male_castrated", "name:张|让-赵|忠-孙|璋-毕|岚-夏|恽-韩|悝-栗|嵩-段|珪-郭|胜-高|望", "character:shichangshi", "die:shichangshi"]],
	taffyold_scs_zhangrang: ["male", "qun", "", ["taffyold_scstaoluan"], ["unseen", "sex:male_castrated", "character:scs_zhangrang", "die:scs_zhangrang"]],
	taffyold_scs_zhaozhong: ["male", "qun", "", ["taffyold_scschiyan"], ["unseen", "sex:male_castrated", "character:scs_zhaozhong", "die:scs_zhaozhong"]],
	taffyold_scs_sunzhang: ["male", "qun", "", ["taffyold_scszimou"], ["unseen", "sex:male_castrated", "character:scs_sunzhang", "die:scs_sunzhang"]],
	taffyold_scs_bilan: ["male", "qun", "", ["taffyold_scspicai"], ["unseen", "sex:male_castrated", "character:scs_bilan", "die:scs_bilan"]],
	taffyold_scs_xiayun: ["male", "qun", "", ["taffyold_scsyaozhuo"], ["unseen", "sex:male_castrated", "character:scs_xiayun", "die:scs_xiayun"]],
	taffyold_scs_hankui: ["male", "qun", "", ["taffyold_scsxiaolu"], ["unseen", "sex:male_castrated", "character:scs_hankui", "die:scs_hankui"]],
	taffyold_scs_lisong: ["male", "qun", "", ["taffyold_scskuiji"], ["unseen", "sex:male_castrated", "character:scs_lisong", "die:scs_lisong"]],
	taffyold_scs_duangui: ["male", "qun", "", ["taffyold_scschihe"], ["unseen", "sex:male_castrated", "character:scs_duangui", "die:scs_duangui"]],
	taffyold_scs_guosheng: ["male", "qun", "", ["taffyold_scsniqu"], ["unseen", "sex:male_castrated", "character:scs_guosheng", "die:scs_guosheng"]],
	taffyold_scs_gaowang: ["male", "qun", "", ["taffyold_scsanruo"], ["unseen", "sex:male_castrated", "character:scs_gaowang", "die:scs_gaowang"]],
	taffyold_dc_zhangmancheng: ["male", "qun", 4, ["taffyold_dclvecheng", "taffyold_dczhongji"], ["character:dc_zhangmancheng", "die:dc_zhangmancheng"]],
	taffyre_xuyou: ["male", "qun", 3, ["nzry_chenglve", "nzry_shicai", "taffyre_nzry_cunmu"], ["character:xuyou", "die:xuyou"]],
	taffyold_zhangzhongjing: ["male", "qun", 3, ["taffyold_jishi", "liaoyi", "binglun"], ["character:zhangzhongjing", "die:zhangzhongjing"]],
	taffyold_sb_huanggai: ["male", "wu", "2/4/2", ["sbkurou", "sbzhaxiang"], ["character:sb_huanggai", "die:sb_huanggai"]],
	taffyold_sb_huangzhong: ["male", "shu", 4, ["taffyold_sbliegong"], ["character:sb_huangzhong", "die:sb_huangzhong"]],
	taffyold_shen_huangzhong: ["male", "shen", 4, ["taffyold_1！5！", "taffyold_chiren"], ["shu", "character:shen_huangzhong", "die:shen_huangzhong"]],
	taffyold_new_simayi: ["male", "shen", 4, ["taffyold_jilin", "taffyold_yingyou", "taffyold_yingtian"], ["wei", "name:司马|懿", "character:new_simayi", "die:new_simayi"]],
	taffyold_xin_simayi: ["male", "shen", 4, ["taffyold_xinrenjie", "taffyold_xinbaiyin", "taffyold_xinlianpo"], ["tempname:shen_simayi", "wei", "name:司马|懿", "character:xin_simayi", "die:xin_simayi"]],
	taffyold_yuechen: ["male", "wei", 4, ["taffyold_dcporui", "taffyold_dcgonghu"], ["character:yuechen", "die:yuechen"]],
	taffyold_ruanyu: ["male", "wei", 3, ["xingzuo", "taffyold_miaoxian"], ["character:ruanyu", "die:ruanyu"]],
	taffyold_zhangrang: ["male", "qun", 3, ["taffyold_taoluan"], ["sex:male_castrated", "character:zhangrang", "die:zhangrang"]],
	taffyold_ol_hujinding: ["female", "shu", 3, ["olqingyuan", "taffyold_olchongshen"], ["character:ol_hujinding", "die:ol_hujinding"]],
	taffyold_dc_zhaoyǎn: ["male", "wei", 4, ["dcfuning", "dcbingji"], ["character:dc_zhaoyǎn", "die:dc_zhaoyǎn"]],
	taffyold_lukai: ["male", "wu", 4, ["taffyold_lkbushi", "taffyold_lkzhongzhuang"], ["character:lukai", "die:lukai"]],
	taffyold_dc_liuli: ["male", "shu", 3, ["taffyold_dcfuli", "dcdehua"], ["character:dc_liuli", "die:dc_liuli"]],
	taffyold_yue_miheng: ["male", "qun", 3, ["taffyold_dcjigu", "dcsirui"], ["character:yue_miheng", "die:yue_miheng"]],
	taffyold_ol_sb_guanyu: ["male", "shu", 4, ["taffyold_olsbweilin", "olsbduoshou"], ["character:ol_sb_guanyu", "die:ol_sb_guanyu"]],
	taffyold_fuqian: ["male", "shu", 4, ["taffyold_jueyong", "taffyold_poxiang"], ["character:fuqian", "die:fuqian"]],
	taffyold_xin_guozhao: ["female", "wei", 3, ["taffyold_yichong", "taffyold_wufei"], ["character:xin_guozhao", "die:xin_guozhao"]],
	taffyold_db_wenyang: ["male", "wei", 4, ["dbquedi", "taffyold_dbzhuifeng", "taffyold_dbchongjian", "dbchoujue"], ["doublegroup:wei:wu", "character:db_wenyang", "die:db_wenyang"]],
	taffyold_shen_caopi: ["male", "shen", 6, ["taffyold_chuyuan", "taffyold_dengji"], ["wei", "character:shen_caopi", "die:shen_caopi"]],
	taffyold_clan_xuncai: ["female", "qun", 3, ["taffyold_clanlieshi", "taffyold_clandianzhan", "clanhuanyin", "clandaojie"], ["clan:颍川荀氏", "character:clan_xuncai", "die:clan_xuncai"]],
	taffyold_shen_xunyu: ["male", "shen", 3, ["taffyold_tianzuo", "taffyold_lingce", "taffyold_dinghan"], ["wei", "clan:颍川荀氏", "character:shen_xunyu", "die:shen_xunyu"]],
	himari: ["female", "shen", 3, ["himari_jianshi", "himari_yiwai", "himari_linghua", "himari_zhensui"], ["qun", "name:明星|日鞠"]],
	taffyold_xunyuxunyou: ["male", "wei", 3, ["taffyold_zhinang", "taffyold_gouzhu"], ["name:荀|彧-荀|攸", "character:xunyuxunyou", "die:xunyuxunyou"]],
	taffyold_tw_shen_lvmeng: ["male", "shen", 3, ["taffyold_twshelie", "taffyold_twgongxin"], ["wu", "character:tw_shen_lvmeng", "die:tw_shen_lvmeng"]],
	taffyold_huan_zhugeguo: ["female", "shu", 3, ["taffyold_rexianyuan", "twlingyin"], ["character:huan_zhugeguo", "die:huan_zhugeguo"]],
	taffyold_mb_wangjing: ["male", "wei", 3, ["mbzujin", "taffyold_mbjiejian"], ["character:mb_wangjing", "die:mb_wangjing"]],
	taffyold_yj_majun: ["male", "wei", 3, ["gongqiao", "taffyold_yjjingyi"], ["character:yj_majun", "die:yj_majun"]],
	taffyold_new_yj_dongzhuo: ["male", "qun", "4/5", ["taffyold_xiongjin", "taffyold_xiawei", "taffyold_baoxi"], ["character:new_yj_dongzhuo", "die:new_yj_dongzhuo"]],
	taffyold_wu_huangfusong: ["male", "qun", 4, ["dcchaozhen", "taffyold_dclianjie", "taffyold_dcjiangxian"], ["name:皇甫|嵩", "character:wu_huangfusong", "die:wu_huangfusong"]],
	taffyold_xurong: ["male", "qun", 4, ["taffyold_xinfu_xionghuo", "taffyold_xinfu_shajue"], ["character:xurong", "die:xurong"]],
	taffyred_xin_jushou: ["male", "qun", "2/3/3", ["taffyred_xinjianying", "taffyred_shibei"]],
	taffyold_shen_pangtong: ["male", "shen", "1/1", ["luansuo", "fengliao", "taffyold_kunyu"], ["character:shen_pangtong", "die:shen_pangtong"]],
	taffyold_v_sunquan: ["male", "wu", 4, ["taffyold_dcwoheng", "taffyold_dcjizheng"], ["zhu", "character:v_sunquan", "die:v_sunquan"]],
	taffyold_huan_caoang: ["male", "wei", "3/4", ["taffyold_twchihui", "taffyold_twfuxi"], ["character:huan_caoang", "die:huan_caoang"]],
	taffyold_ol_nanhualaoxian: ["male", "qun", 4, ["taffyold_olqingshu", "taffyold_olshoushu", "taffyold_olhedao"], ["character:ol_nanhualaoxian", "die:ol_nanhualaoxian"]],
	taffyold_ol_sb_dongzhuo: ["male", "qun", 5, ["taffyold_olguanbian", "taffyold_olxiongni", "taffyold_olfengshang", "olzhibin"], ["zhu", "character:ol_sb_dongzhuo", "die:ol_sb_dongzhuo"]],
	taffyold_pangfengyi: ["female", "shu", 3, ["taffyold_dcyitong", "taffyold_dcpeiniang"], ["character:pangfengyi", "die:pangfengyi"]],
	taffyold_hanshiwuhu: ["male", "wei", 5, ["oljuejue", "olpimi"], ["name:韩|德‌-韩|瑛-韩|瑶-韩|琼-韩|琪", "character:hanshiwuhu", "die:hanshiwuhu"]],
	taffy_liubianxing: ["male", "shen", "3/4/1", ["taffy_shelie"], ["wu", "character:tw_shen_lvmeng", "die:tw_shen_lvmeng", "InitFilter:noZhuHp:noZhuSkill"]],
	mutsumi: ["female", "shen", 3, ["mutsumi_songyue", "mutsumi_wuyan", "mutsumi_huge"], ["qun", "name:若叶|睦"]],
	mortis: ["female", "shen", 4, ["mortis_renou", "mortis_yanyi", "mortis_shige"], ["qun", "name:null|Mortis"]],
	taffyps_shen_jiangwei: ["male", "shen", 4, ["taffyps_jiufa", "taffyps_tianren", "taffyps_pingxiang"], ["shu", "character:shen_jiangwei", "die:shen_jiangwei"]],
	taffype_guozhao: ["female", "wei", 3, ["taffype_pianchong", "taffype_zunwei"], ["character:guozhao", "die:guozhao"]],
	taffyold_wechat_ji_guanyu: ["male", "shu", 4, ["taffyold_wechatyihan", "taffyold_wechatwuwei"]],
	taffyold_wechat_ji_caocao: ["male", "wei", 4, ["taffyold_wechatdelu", "taffyold_wechatzhujiu"]],
	taffyold_wechat_ji_zhugeliang: ["male", "shu", 3, ["taffyold_wechatsangu", "taffyold_wechatyanshi"], ["name:诸葛|亮"]],
	taffyold_wechat_ji_sunce: ["male", "wu", 4, ["taffyold_wechattaoni", "taffyold_wechatpingjiang", "taffyold_wechatdingye"], ["zhu"]],
	taffyshen_shamoke: ["male", "shen", 4, ["taffyshen_gzjili"], ["shu", "name:null|null", "character:ty_shamoke", "die:shamoke"]],
	taffyre_shamoke: ["male", "shu", 4, ["taffyre_gzjili"], ["name:null|null", "character:shamoke", "die:shamoke"]],
	taffyold_pot_taishici: ["male", "wu", 4, ["taffyold_pothanzhan", "taffyold_potzhanlie", "taffyold_potzhenfeng"], ["character:pot_taishici", "die:pot_taishici"]],
	taffyold_dc_sp_zhurong: ["female", "qun", 4, ["taffyold_dcremanhou", "taffyold_dcretanluan"], ["name:null|null", "character:dc_sp_zhurong", "die:dc_sp_zhurong"]],
	taffyold_liujinliupei: ["female", "wei", 3, ["taffyold_dcllqixin", "dcjiusi"], ["name:刘|衿-刘|佩", "character:liujinliupei", "die:liujinliupei"]],
	taffyold_pot_chendao: ["male", "shu", 4, ["taffyold_potwanglie", "taffyold_pothongyi"], ["character:pot_chendao", "die:pot_chendao"]],
	taffyold_ol_miheng: ["male", "qun", 4, ["taffyold_olkuangjuan", "taffyold_olfeibian"], ["character:ol_miheng", "die:ol_miheng"]],
	taffyold_clan_yangxiu: ["male", "wei", 3, ["taffyold_clanjiewu", "taffyold_clangaoshi", "clanquhuo"], ["clan:弘农杨氏", "character:clan_yangxiu", "die:clan_yangxiu"]],
	taffywn_zhanghe: ["male", "wei", 4, ["taffywn_qiaobian"]],
	taffyold_dc_zhugejun: ["male", "shu", 3, ["dcgengdu", "taffyold_dcgumai"], ["character:dc_zhugejun", "die:dc_zhugejun"]],
	taffyold_dc_xiahouxuan: ["male", "wei", 3, ["dcboxuan", "taffyold_dcyizheng", "taffyold_dcguilin"], ["name:夏侯|玄", "character:dc_xiahouxuan", "die:dc_xiahouxuan"]],
	taffyold_pot_weiyan: ["male", "shu", 4, ["taffyold_potzhongao", "taffyold_potzhuangshi", "taffyold_potyinzhan"], ["character:pot_weiyan", "die:pot_weiyan"]],
	taffyold_pot_yuji: ["male", "qun", 3, ["taffyold_potdaozhuan", "taffyold_potfuji"], ["character:pot_yuji", "die:pot_yuji"]],
	taffyold_ol_sb_yl_luzhi: ["male", "qun", 4, ["taffyold_olsibing", "taffyold_olliance"], ["character:ol_sb_yl_luzhi", "die:ol_sb_yl_luzhi"]],
	taffyzunxiang_xiahouxuan: ["male", "wei", 3, ["taffyzunxiang_olhuanfu", "olqingyi", "taffyzunxiang_olzeyue"], ["name:夏侯|玄,", "character:xiahouxuan", "die:xiahouxuan"]],
	aruijier: ["female", "shen", "", [], ["unseen", "qun"]],
};

export default characters;
