const characterReplaces = {
	wu_zhugeliang: ["wu_zhugeliang", "taffyold_wu_zhugeliang"],
	guanning: ["guanning", "taffydc_guanning"],
	xushao: ["xushao", "jsrg_xushao", "taffydc_xushao", "taffyre_xushao"],
	niufudongxie: ["tw_niufudongxie", "taffyold_tw_niufudongxie"],
	zhangmancheng: ["dc_zhangmancheng", "tw_zhangmancheng", "taffyold_tw_zhangmancheng", "taffyold_dc_zhangmancheng"],
	sunquan: ["sunquan", "re_sunquan", "v_sunquan", "dc_sunquan", "xin_sunquan", "sb_sunquan", "jd_sb_sunquan", "ty_sunquan", "ps_sunquan", "pe_jun_sunquan", "taffyhuiwan_sunquan", "taffyhuiwanplus_sunquan", "taffyold_v_sunquan", "taffyoldtwo_v_sunquan"],
	shen_caocao: ["shen_caocao", "old_caocao", "ca_shen_caocao", "taffymb_shen_caocao"],
	shen_simayi: ["shen_simayi", "xin_simayi", "new_simayi", "taffyold_baby_shen_simayi", "taffyold_xin_simayi", "taffyold_new_simayi"],
	ruiji: ["ruiji", "dc_ruiji", "taffyold_ruiji"],
	tengfanglan: ["tengfanglan", "dc_tengfanglan", "taffyold_tengfanglan"],
	feiyi: ["ol_feiyi", "feiyi", "tw_feiyi", "taffyold_ol_feiyi"],
	caopi: ["caopi", "v_caopi", "re_caopi", "sb_caopi", "tw_sb_caopi", "huan_caopi", "ps_caopi", "sxrm_caopi", "pe_jun_caopi", "taffyold_sb_caopi"],
	yuantanyuanshang: ["yuantanyuanshang", "yuantanyuanxiyuanshang", "taffyold_yuantanyuanshang"],
	zhanghua: ["zhanghua", "taffyold_zhanghua"],
	ol_pengyang: ["ol_pengyang", "sp_pengyang", "taffyold_ol_pengyang"],
	sp_zhugeliang: ["sp_zhugeliang", "ol_sp_zhugeliang", "re_sp_zhugeliang", "sb_sp_zhugeliang", "jd_sb_sp_zhugeliang", "taffyold_sb_sp_zhugeliang", "taffyoldtwo_sb_sp_zhugeliang"],
	guanyu: ["guanyu", "re_guanyu", "jsp_guanyu", "ol_sb_guanyu", "wu_guanyu", "dc_jsp_guanyu", "sb_guanyu", "tw_jsp_guanyu", "xia_guanyu", "jsrg_guanyu", "jd_sb_guanyu", "drag_guanyu", "ty_guanyu", "jx_guanyu", "ps_guanyu", "old_guanyu", "junk_guanyu", "taffyold_sb_guanyu", "taffyold_ol_sb_guanyu"],
	bailingyun: ["bailingyun", "taffyold_bailingyun"],
	zhonghui: ["zhonghui", "xin_zhonghui", "re_zhonghui", "old_zhonghui", "pe_zhonghui", "clan_zhonghui", "yj_zhonghui", "std_zhonghui", "taffyold_clan_zhonghui"],
	ol_luyusheng: ["ol_luyusheng", "luyusheng", "mb_luyusheng", "ns_luyusheng", "taffyold_ol_luyusheng"],
	shen_lusu: ["shen_lusu", "taffyold_shen_lusu"],
	wu_guanyu: ["wu_guanyu", "taffyold_wu_guanyu"],
	shen_huatuo: ["dc_shen_huatuo", "shen_huatuo", "taffyold_dc_shen_huatuo"],
	shen_xuzhu: ["shen_xuzhu", "taffyold_shen_xuzhu"],
	tenggongzhu: ["tenggongzhu", "taffyold_tenggongzhu"],
	baoxin: ["tw_baoxin", "baoxin", "taffyold_tw_baoxin"],
	shichangshi: ["shichangshi", "taffyold_shichangshi"],
	xuyou: ["xuyou", "sp_xuyou", "jsrg_xuyou", "yj_xuyou", "junk_xuyou", "taffyre_xuyou"],
	zhangzhongjing: ["zhangzhongjing", "taffyold_zhangzhongjing"],
	huanggai: ["huanggai", "re_huanggai", "sb_huanggai", "dc_sb_huanggai", "taffyold_sb_huanggai"],
	huangzhong: ["re_huangzhong", "ol_huangzhong", "sb_huangzhong", "huangzhong", "jsrg_huangzhong", "yj_huangzhong", "taffyold_sb_huangzhong"],
	shen_huangzhong: ["shen_huangzhong", "taffyold_shen_huangzhong"],
	yuechen: ["yuechen", "taffyold_yuechen"],
	ruanyu: ["ruanyu", "taffyold_ruanyu"],
	zhangrang: ["ol_zhangrang", "zhangrang", "ol_sb_zhangrang", "star_zhangrang", "junk_zhangrang", "ps_zhangrang", "taffyold_zhangrang"],
	hujinding: ["dc_hujinding", "ol_hujinding", "hujinding", "taffyold_ol_hujinding"],
	zhaoyǎn: ["zhaoyǎn", "dc_zhaoyǎn", "taffyold_dc_zhaoyǎn"],
	lukai: ["ol_lukai", "lukai", "taffyold_lukai"],
	liuli: ["dc_liuli", "taffyold_dc_liuli"],
	miheng: ["ol_miheng", "yue_miheng", "re_miheng", "miheng", "scl_miheng", "taffyold_yue_miheng", "taffyold_ol_miheng"],
	fuqian: ["fuqian", "taffyold_fuqian"],
	guozhao: ["guozhao", "xin_guozhao", "jsrg_guozhao", "ol_guozhao", "taffyold_xin_guozhao", "taffype_guozhao"],
	wenyang: ["wenyang", "db_wenyang", "diy_wenyang", "std_db_wenyang", "taffyold_db_wenyang"],
	shen_caopi: ["shen_caopi", "taffyold_shen_caopi"],
	clan_xuncai: ["clan_xuncai", "taffyold_clan_xuncai"],
	shen_xunyu: ["shen_xunyu", "taffyold_shen_xunyu"],
	xunyuxunyou: ["xunyuxunyou", "taffyold_xunyuxunyou"],
	shen_lvmeng: ["shen_lvmeng", "tw_shen_lvmeng", "mini_lvmeng", "taffyold_tw_shen_lvmeng"],
	zhugeguo: ["zhugeguo", "tw_zhugeguo", "yue_zhugeguo", "huan_zhugeguo", "taffyold_huan_zhugeguo"],
	mb_wangjing: ["mb_wangjing", "taffyold_mb_wangjing"],
	majun: ["majun", "yj_majun", "cx_majun", "qq_majun", "old_majun", "taffyold_yj_majun"],
	dongzhuo: ["dongzhuo", "ol_dongzhuo", "re_dongzhuo", "star_dongzhuo", "jsrg_dongzhuo", "ol_sb_dongzhuo", "sp_dongzhuo", "yj_dongzhuo", "new_yj_dongzhuo", "taffyold_new_yj_dongzhuo", "taffyold_ol_sb_dongzhuo"],
	wu_huangfusong: ["wu_huangfusong", "taffyold_wu_huangfusong"],
	xurong: ["xurong", "taffyold_xurong"],
	yj_jushou: ["yj_jushou", "re_jushou", "xin_jushou", "dc_sb_jushou", "taffyred_xin_jushou"],
	shen_pangtong: ["shen_pangtong", "taffyold_shen_pangtong"],
	caoang: ["caoang", "dc_sb_caoang", "huan_caoang", "taffyold_huan_caoang"],
	nanhualaoxian: ["re_nanhualaoxian", "ol_nanhualaoxian", "nanhualaoxian", "jsrg_nanhualaoxian", "taffyold_ol_nanhualaoxian"],
	pangfengyi: ["pangfengyi", "taffyold_pangfengyi"],
	shen_jiangwei: ["shen_jiangwei", "taffyps_shen_jiangwei"],
	wechat_zhiyin_guanyu: ["wechat_zhiyin_guanyu", "taffyold_wechat_ji_guanyu"],
	wechat_zhiyin_caocao: ["wechat_zhiyin_caocao", "taffyold_wechat_ji_caocao"],
	wechat_zhiyin_zhugeliang: ["wechat_zhiyin_zhugeliang", "taffyold_wechat_ji_zhugeliang"],
	wechat_zhiyin_sunce: ["wechat_zhiyin_sunce", "taffyold_wechat_ji_sunce"],
	shamoke: ["shamoke", "ty_shamoke", "taffyshen_shamoke", "taffyre_shamoke"],
	taishici: ["taishici", "re_taishici", "ol_sb_taishici", "sp_taishici", "re_sp_taishici", "pot_taishici", "taffyold_pot_taishici"],
	zhurong: ["zhurong", "ol_zhurong", "re_zhurong", "sb_zhurong", "dc_sp_zhurong", "taffyold_dc_sp_zhurong"],
	liujinliupei: ["liujinliupei", "taffyold_liujinliupei"],
	chendao: ["chendao", "pot_chendao", "ns_chendao", "old_chendao", "taffyold_pot_chendao"],
	yangxiu: ["yangxiu", "clan_yangxiu", "taffyold_clan_yangxiu"],
	zhanghe: ["zhanghe", "re_zhanghe", "sp_ol_zhanghe", "yj_zhanghe", "sp_zhanghe", "sb_zhanghe", "tw_yj_zhanghe", "huan_zhanghe", "jsrg_zhanghe"],
	tw_zhugejun: ["tw_zhugejun", "dc_zhugejun", "taffyold_dc_zhugejun"],
	xiahouxuan: ["xiahouxuan", "dc_xiahouxuan", "pe_xiahouxuan", "taffyold_dc_xiahouxuan", "taffyzunxiang_xiahouxuan"],
	weiyan: ["re_weiyan", "ol_weiyan", "weiyan", "yj_weiyan", "huan_weiyan", "pot_weiyan", "taffyold_pot_weiyan"],
	yuji: ["xin_yuji", "re_yuji", "yuji", "pot_yuji", "diy_yuji", "ns_yuji", "ns_yujisp", "taffyold_pot_yuji"],
	yl_luzhi: ["yl_luzhi", "ol_sb_yl_luzhi", "sb_yl_luzhi", "tw_yl_luzhi", "jsrg_yl_luzhi", "taffyold_ol_sb_yl_luzhi"],
	wuhujiang: ["wuhujiang", "hanshiwuhu", "taffyold_hanshiwuhu"],
	renwan: ["renwan", "taffyold_renwan"],
};

export default characterReplaces;
